Refactor CosineSimiliarity
kakaobrain/trident pull request #111
Opened 2023-09-07 10:06 UTC by mejai1206

## 🙏 Describe the pull request

CosineSimiliarity를 리팩토링했습니다.

## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

2023-09-07 10:36 UTC, daemyung requested changes

2023-09-07 10:36 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +        num_batches: tl.int32,
지금 코딩 스타일은 `num_batches`를 받지 않습니다. Linear 참고 부탁드려요.

2023-09-07 10:36 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +        dim_order_0: tl.constexpr,
`dim_order_n`이 필요한 이유가 무엇인가요?

2023-09-07 10:36 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +        x1_block_ptr = tl.make_block_ptr(
block 생성이 이상한 것 같아요. cosine similiarty를 계산해야할 데이터를 제일 마지막 축으로 바꿔주세요.

2023-09-07 10:36 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +        i = pid // output_x_size
`i`, `j`를 좀 더 의미있는 변수명으로 바꿔주세요.

2023-09-07 11:38 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +        num_batches: tl.int32,
이거 내일 이야기 하시죠.

2023-09-08 00:06 UTC, mejai1206 commented on trident/kernel/cosine_similarity.py
> +        x1_block_ptr = tl.make_block_ptr(
block의 마지막 축 지정은 나중에 입력 텐서의 차원이 추가될 때 `tl.sum()`의 `axis`를 바꿔줘야 할 것 같은데,
반면 0번째 축 지정은 입력 텐서의 차원이 더 추가 되어도
`tl.sum()`을 쓸때 항상 `axis`를 `0`으로 고정할 수 있어서 `axis`를 바꾸지 않아도 되는 점이 좋아보여서 0번째 축으로 지정했습니다.

혹시 0번째 축 지정은 좋은 방식은 아닐까요?

2023-09-08 00:15 UTC, mejai1206 commented on trident/kernel/cosine_similarity.py
> +        dim_order_0: tl.constexpr,
`block_pointer` 생성시, `shape`과 `stride`에 따라 차원의 순서가 바뀌어서 넣게 되었습니다.
y, x 순서로 만들땐 `order=(1, 0)`을 주지만 x, y 순서로 만들땐 `order=(0, 1)` 주는 코드들을 참고 하였습니다.

2023-09-08 00:18 UTC, mejai1206 commented on trident/kernel/cosine_similarity.py
> +        i = pid // output_x_size
`output_y`, `output_x`로 수정하도록 하겠습니다.

2023-09-08 00:19 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +        x1_block_ptr = tl.make_block_ptr(
아뇨 Cosine Similarity를 보니 블락 생성이 이상하게 생각되진 않았습니다. 변수명을 잘못 지어서 그런것 같아요.

2023-09-08 01:49 UTC, mejai1206 commented on trident/kernel/cosine_similarity.py
> +        num_batches: tl.int32,
`z_size`로 변경하였습니다.

2023-09-08 01:55 UTC, ansteve approved these changes
LGTM

2023-09-08 02:04 UTC, daemyung requested changes

2023-09-08 02:04 UTC, daemyung commented on trident/operation/cosine_similarity.py
> +    def __size_and_stride(input: torch.Tensor, dim: torch.int32):
이 함수를 `util.size_and_stride`에 통합시켜주세요. `input`의 차원을 보고 리턴하는 값을 다르게 하면 되요.

2023-09-08 02:04 UTC, daemyung commented on trident/operation/cosine_similarity.py
> +            dim_order = (1, 2, 0)
`dim_order`는 필요 없는 정보인 것 같아요. 이것이 항상 이런 값인 이유가 있나요?

2023-09-08 02:04 UTC, daemyung commented on tests/test_cosine_similarity.py
> +    input = torch.randn(z_size, y_size, x_size, **factory_kwargs)
`x1`, `x2`로 통일시켜주세요. 아니면 CosineSimilarity를 `input`, `other`로 바꿔주세요.

2023-09-08 02:04 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +        output_y = pid // output_x_size
`num_output_y`, `num_output_x`가 적절해 보입니다.

2023-09-08 02:04 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +        output_y = pid // output_x_size
`num_output_y`, `num_output_x`가 적절해 보입니다.

2023-09-08 02:08 UTC, mejai1206 commented on tests/test_cosine_similarity.py
> +    input = torch.randn(z_size, y_size, x_size, **factory_kwargs)
`x1`, `x2` 로 변경하겠습니다.

2023-09-08 02:10 UTC, mejai1206 commented on trident/kernel/cosine_similarity.py
> +        output_y = pid // output_x_size
`num_output_y`, `num_output_x` 로 변경하겠습니다.

2023-09-08 02:13 UTC, mejai1206 commented on trident/operation/cosine_similarity.py
> +            dim_order = (1, 2, 0)
원형인 `z, y, x` 순일땐  `2, 1, 0` 을 넣고
여기선 y와 z가 바뀌어서 `1, 2, 0` 으로 넣게 되었습니다.

커널에서 항상 `2, 1, 0`을 입력하고, `dim_order`를 빼도록 할까요?

2023-09-08 02:17 UTC, daemyung commented on trident/operation/cosine_similarity.py
> +            dim_order = (1, 2, 0)
넵

2023-09-08 02:18 UTC, mejai1206 commented on trident/operation/cosine_similarity.py
> +            dim_order = (1, 2, 0)
넵 `dim_order` 를 삭제하고 `util.size_and_stride` 와 통합 하도록 하겠습니다.

2023-09-08 02:31 UTC, mejai1206 commented on trident/operation/cosine_similarity.py
> +            dim_order = (1, 2, 0)
음..  전 `size_and_stride`에서 아래와 같은 경우는 `block_pointer`를 사용할때 텐서를 전치해서 해석하는 것으로 이해하고 있었습니다.

x_size, y_size = input.shape
y_stride = input.stride(1)
x_stride = input.stride(0)

텐서를 전치해서 해석할 경우엔 order도 함께 바꿔주는 코드를 트리톤 예시에서 봤습니다.

2023-09-08 04:24 UTC, daemyung commented on trident/operation/cosine_similarity.py
> +            dim_order = (1, 2, 0)
전치하더라도 우선순위를 그렇게 주고 싶을 수 있는거죠.

2023-09-08 04:37 UTC, mejai1206 commented on trident/operation/cosine_similarity.py
> +            dim_order = (1, 2, 0)
`dim_order`를 삭제하고 `order=(2, 1, 0)` 으로 통일하였습니다.

2023-09-08 04:38 UTC, daemyung commented on trident/operation/cosine_similarity.py
> +            dim_order = (1, 2, 0)
통일하지 않아도 되요. 필요한 부분은 (1, 2, 0)으로 둬도 되요. 저 함수에서 저 order를 준다는것은 정형화 되어 있다는 말인데 실제 메모리를 불러오면서 order가 정형화될 수 없다고 생각하거든요.

2023-09-08 04:46 UTC, daemyung requested changes

2023-09-08 04:46 UTC, daemyung commented on benchmarks/benchmark_cosine_similarity.py
> +    x1.requires_grad = x2.requires_grad = True
역전파 벤치마크도 `benchmark_silu` 참고해서 고쳐주세요.

2023-09-08 04:46 UTC, daemyung commented on tests/test_cosine_similarity.py
> +        x1_ = x1.clone()
안의 변수는 `i, j, k`로 사용됩니다.

2023-09-08 04:46 UTC, daemyung commented on tests/test_cosine_similarity.py
> +        target_dim = (z_size, y_size)
`target`을 `grad_ouput`으로 바꿔주세요. 제가 예전에 `target`을 썼는데 잘못된 표현이었습니다.

2023-09-08 04:46 UTC, daemyung commented on tests/test_cosine_similarity.py
> +        return [x1_.grad, x2_.grad]
Tuple 말고 `x1_.grad, x2_.grad`로 리턴해주세요.

2023-09-08 04:46 UTC, daemyung commented on tests/test_cosine_similarity.py
>      grad_a = train(torch.nn.CosineSimilarity(dim=dim))
```
(x, y) = train(torch.nn.CosineSimilarity(dim))
(a, b) = train(trident.CosineSimilarity(dim))
```
로 변경해주세요. `dim`의 경우는 변수명 자체가 `dim`이기 때문에 특별한 이유가 없는한 `dim=dim`이라고 쓸필요 없어요.

2023-09-08 04:46 UTC, daemyung commented on trident/kernel/cosine_similarity.py
>          eps,
eps에 대한 타입이 빠져있습니다.

2023-09-08 04:46 UTC, daemyung commented on trident/operation/cosine_similarity.py
> +
불필요한 줄바꿈입니다.

2023-09-08 04:46 UTC, daemyung commented on trident/operation/cosine_similarity.py
> +
불필요한 줄바꿈입니다.

2023-09-08 04:46 UTC, daemyung commented on trident/util/util.py
> +    if input.dim() == 3:
이런 처리를 할때는 1부터 증가하는 방식이 좋습니다. 순서대로 작성해주세요. 지원되지 않는 `dim`의 경우는 예외를 발생해주세요.

2023-09-08 04:46 UTC, daemyung commented on trident/util/util.py
> +def output_and_along_dim_size(input: torch.Tensor, dim: int):
이 함수는 cosine similarity에만 필요한 함수처럼 보이는데요. 일반적으로 적용될 수 있나요?

2023-09-08 04:52 UTC, mejai1206 commented on trident/operation/cosine_similarity.py
> +            dim_order = (1, 2, 0)
(1, 2, 0) 이런식의 순서는 제가 order에 대해서 잘못 이해한 부분으로 생각됩니다.
현재 코드에선 `block_pointer` 생성시  `order=(2, 1, 0)` 이외의 순서는 둘 필요가 없다고 생각이 들었습니다.

그래서 dim_order 이런것을 넘기지 않고 아래 코드처럼 고정적으로 사용하고자 합니다.

```
        grad_x1_block_ptr = tl.make_block_ptr(
            grad_x1_ptr,
            shape=(z_size, y_size, x_size),
            strides=(z_stride, y_stride, x_stride),
            offsets=(0, num_output_y, num_output_x),
            block_shape=(block_size, 1, 1),
            order=(2, 1, 0),
        )
```

2023-09-08 04:59 UTC, mejai1206 commented on tests/test_cosine_similarity.py
> +        target_dim = (z_size, y_size)
수정하겠습니다.

2023-09-08 04:59 UTC, mejai1206 commented on tests/test_cosine_similarity.py
> +        return [x1_.grad, x2_.grad]
수정하겠습니다.

2023-09-08 04:59 UTC, mejai1206 commented on tests/test_cosine_similarity.py
> +        x1_ = x1.clone()
i, j로 수정하겠습니다.

2023-09-08 05:00 UTC, mejai1206 commented on benchmarks/benchmark_cosine_similarity.py
> +    x1.requires_grad = x2.requires_grad = True
넵 수정하겠습니다.

2023-09-08 05:05 UTC, mejai1206 commented on tests/test_cosine_similarity.py
>      grad_a = train(torch.nn.CosineSimilarity(dim=dim))
넵 수정하겠습니다.

2023-09-08 05:08 UTC, mejai1206 commented on trident/util/util.py
> +def output_and_along_dim_size(input: torch.Tensor, dim: int):
3차원 데이터를 2차원으로 줄이는 연산이 추가되면 쓰일 것 같습니다.
예를 들면 3차원 input에 dim=0을 입력하면 output은 `y_size, x_size` 이고, 
`dim=1`을 입력하면 output은 `z_size, x_size`가 됩니다.

2023-09-08 05:09 UTC, mejai1206 commented on trident/util/util.py
> +    if input.dim() == 3:
수정하겠습니다.

2023-09-08 05:11 UTC, mejai1206 commented on trident/operation/cosine_similarity.py
> +
47번째줄의 개행 삭제하겠습니다.

2023-09-08 05:13 UTC, mejai1206 commented on trident/kernel/cosine_similarity.py
>          eps,
`tl.float32`으로 추가하겠습니다.

2023-09-08 06:11 UTC, daemyung commented on trident/util/util.py
> +def output_and_along_dim_size(input: torch.Tensor, dim: int):
일반적이지 않은 것 같습니다. cosine similarity 안으로 옮겨주세요.

2023-09-08 06:21 UTC, mejai1206 commented on trident/util/util.py
> +def output_and_along_dim_size(input: torch.Tensor, dim: int):
수정하였습니다.

2023-09-08 06:23 UTC, daemyung requested changes

2023-09-08 06:23 UTC, daemyung commented on trident/operation/cosine_similarity.py
> +        output_y_size, output_x_size, size_along_dim = CosineSimilarity.__output_and_along_dim_size(x1, dim)
함수 이름을 `__output_size_and_size_along_dim`으로 변경 부탁드려요. `__output_and_along_dim_size`은 출력과 along_dim_size를 반환하는걸로 이해되요.

2023-09-08 06:24 UTC, daemyung commented on trident/util/util.py
> +        raise NotImplementedError("{dim} is an unsupported dimension.")
`ValueError`가 더 적합하겠네요. 메세지는 f"{dim} is not supported."

2023-09-08 06:24 UTC, mejai1206 commented on trident/operation/cosine_similarity.py
> +        output_y_size, output_x_size, size_along_dim = CosineSimilarity.__output_and_along_dim_size(x1, dim)
`__output_size_and_size_along_dim` 로 수정하였습니다.

2023-09-08 06:26 UTC, mejai1206 commented on trident/util/util.py
> +        raise NotImplementedError("{dim} is an unsupported dimension.")
`ValueError(f"{dim} is not supported.")` 로 수정하였습니다.

2023-09-08 06:27 UTC, daemyung approved these changes
LGTM

2023-09-08 07:17 UTC, merged