Fix BatchNorm to support 3D input
kakaobrain/trident pull request #123
Opened 2023-09-12 04:40 UTC by ansteve

## 🙏 Describe the pull request

3D 입력 처리를 위한 수정입니다.

## ✅ Checklist

- [ ] Code follows the project's coding conventions and style.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated, if necessary.

2023-09-12 05:04 UTC, ansteve commented
변수 이름을 `(num_batches, y_size, x_size)` 대신에 `(num_batches, num_channels, sequence_length)`로 사용한 이유는 향후 PR에서 4D 입력을 받는 `BatchNorm2d` 를 작업하려고 하는데, 그때 `(num_batches, num_channels, y_size, x_size)` 를 사용하고 싶어서입니다.

2023-09-12 05:32 UTC, mejai1206 commented on tests/test_batch_norm.py
> +    inp = torch.randn(num_batches, num_channels, sequence_length, device=device)
`inp`이나 `m`와 같은 변수명들이 축약어가 아니면 더 좋을 것 같습니다.

2023-09-12 07:07 UTC, ansteve commented on tests/test_batch_norm.py
> +    inp = torch.randn(num_batches, num_channels, sequence_length, device=device)
네 수정하겠습니다

2023-09-12 07:34 UTC, mejai1206 approved these changes
LGTM

2023-09-12 08:12 UTC, daemyung requested changes

2023-09-12 08:12 UTC, daemyung commented on benchmarks/benchmark_batch_norm.py
> +        lyr = torch.nn.BatchNorm1d(num_channels, affine=True, dtype=torch.float32, device="cuda")
`backward` 벤치마크를 다른 벤치마크 참고해서 수정해주세요.

2023-09-12 08:12 UTC, daemyung commented on tests/test_batch_norm.py
> +    layer_torch = torch.nn.BatchNorm1d(num_channels, affine=affine, device=device)
테스트도 다른 함수를 사용해서 작성해 주세요.

2023-09-12 08:12 UTC, daemyung commented on tests/test_batch_norm.py
> +def test_function(num_batches, num_channels, sequence_length, training, device):
test_function은 없어졌어요. 다른 테스트 참고해서 테스트 구현해주세요.

2023-09-12 08:12 UTC, daemyung commented on tests/test_batch_norm.py
> +@pytest.mark.parametrize("num_batches, num_channels, sequence_length, affine", [(3, 20, 100, True), (7, 99, 10, False)])
`num_channel`은 `y_size`, `sequence_len`은 `x_size`로 바꿔주세요. `batch`만 특별하게 나타내고 다른 것은 `x, y, z`차원으로 표시해요.

2023-09-12 08:12 UTC, daemyung commented on tests/test_batch_norm.py
> +    layer_torch = torch.nn.BatchNorm1d(num_channels, affine=affine, device=device)
`test_backward`도 다른 테스트 함수 참고해서 작성해 주세요.

2023-09-12 08:12 UTC, daemyung commented on trident/function/function.py
> +    return operation.BatchNorm.apply(input, weight, bias, eps, running_mean, running_var)
`running_mean`, `running_var`의 처리도 BatchNorm 안에서 처리 부탁드려요.

2023-09-12 08:12 UTC, daemyung commented on trident/function/function.py
> +    return operation.BatchNorm.apply(input, weight, bias, eps, running_mean, running_var)
파라미터의 순서를 일치시켜주세요. InstanceNorm 참고해주세요.

2023-09-12 08:12 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        output_ptr: tl.tensor,
`mean`, `var`의 계산이 오래걸립니다. `forward`에서 계산하고 캐싱해서 `backward`에서 사용해주세요.

2023-09-12 08:12 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        sequence_block_size: tl.constexpr,
`sequence_block_size`는 텐서에서 x축이니까 `x_block_size`로 바꿔주세요.

2023-09-12 08:12 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        num_channels: tl.constexpr,
batch를 제외하고는 x, y 용어를 사용해주세요.

2023-09-12 08:12 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        num_batches: tl.constexpr,
블록 크기를 제외한 데이터들의 타입들이 `tl.constexpr`인 이유가 있을까요?

2023-09-12 08:12 UTC, daemyung commented on trident/module.py
> +            self.running_mean = torch.mean(inp, dim=(0, 2)) * self.momentum + self.running_mean * (1 - self.momentum)
이 계산도 InstanceNorm 참고해서 BatchNorm안에서 수행해주세요.

2023-09-13 02:05 UTC, kakao-steve-ai commented on benchmarks/benchmark_batch_norm.py
> +        lyr = torch.nn.BatchNorm1d(num_channels, affine=True, dtype=torch.float32, device="cuda")
네 수정하겠습니다

2023-09-13 02:05 UTC, kakao-steve-ai commented on tests/test_batch_norm.py
> +@pytest.mark.parametrize("num_batches, num_channels, sequence_length, affine", [(3, 20, 100, True), (7, 99, 10, False)])
네 수정하겠습니다

2023-09-13 02:05 UTC, kakao-steve-ai commented on tests/test_batch_norm.py
> +def test_function(num_batches, num_channels, sequence_length, training, device):
네 수정하겠습니다

2023-09-13 02:05 UTC, ansteve commented on trident/kernel/batch_norm.py
> +        num_batches: tl.constexpr,
특별한 이유 없습니다. 수정하겠습니다.

2023-09-13 06:14 UTC, ansteve commented on trident/kernel/batch_norm.py
> +        output_ptr: tl.tensor,
수정했습니다.

2023-09-13 06:53 UTC, daemyung requested changes

2023-09-13 06:53 UTC, daemyung commented on tests/test_batch_norm.py
> +        torch.nn.functional.batch_norm(input, running_mean=None, running_var=None, training=True),
파이토치와 사용 방법이 다른 이유가 있나요?

2023-09-13 06:53 UTC, daemyung commented on tests/test_batch_norm.py
> +def test_running_values(num_batches, y_size, x_size, device):
이 테스트는 `test_forward`에 포함될 수 있어요. `test_instance_norm.py` 참고 부탁드려요.

2023-09-13 06:53 UTC, daemyung commented on trident/function/function.py
> +    return operation.BatchNorm.apply(input, running_mean, running_var, weight, bias, momentum, eps)
`training` 변수는 필요 없나요?

2023-09-13 06:53 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        mean_ptr: tl.tensor,
저희 코딩 스타일은 아규먼트 순서가 출력이 먼저 옵니다. `mean_ptr`, `var_ptr`을 `output_ptr` 다음으로 옮겨주세요.

2023-09-13 06:53 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        y_size: tl.int32,
`num_batches`, `y_size`, `x_size`는 `input_ptr`과 관련된 데이터이니 `input_ptr` 다음으로 옮겨주세요.

2023-09-13 06:53 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        )
`block_ptr` 선언 후에 줄바꿈이 필요해 보입니다.

2023-09-13 06:53 UTC, daemyung commented on trident/kernel/batch_norm.py
> +
불필요한 줄바꿈인것 같아요.

2023-09-13 06:53 UTC, daemyung commented on trident/kernel/batch_norm.py
> +
불필요한 줄바꿈인것 같아요.

2023-09-13 06:53 UTC, daemyung commented on trident/operation/batch_norm.py
> +        eps: float,
torch.float으로 변경해주세요.

2023-09-13 06:53 UTC, daemyung commented on trident/operation/batch_norm.py
> +        batch_block_size = triton.next_power_of_2(num_batches)
`batch_block_size`, `x_block_size`는 인라인처리하는게 가독성에 더 좋을것 같습니다.

2023-09-13 06:53 UTC, daemyung commented on trident/operation/batch_norm.py
> +        batch_block_size = triton.next_power_of_2(num_batches)
`batch_block_size`, `x_block_size`는 인라인처리하는게 가독성에 더 좋을것 같습니다.

2023-09-13 06:53 UTC, daemyung commented on trident/operation/batch_norm.py
> +        mean = torch.empty(y_size, dtype=input.dtype, device=input.device)
`dtype=input.dtype, device=input.device`가 중복적으로 사용되면 `factory_kwargs`를 선언해서 사용해주세요. 타이핑을 줄일 수 있어요.

2023-09-13 06:53 UTC, daemyung commented on trident/module.py
> +            self.running_var = torch.nn.Parameter(torch.empty(num_features, **factory_kwargs).fill_(1))
초기화 하는 것은 `reset_parameters` 함수를 만들어서 수행해주세요. `reset_parameters`를 찾아보면 어떻게 선언하고 사용하는지 확인할 수 있습니다.

2023-09-13 06:53 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        tl.store(grad_input_block_ptr, grad_input, boundary_check=(0, 1))
152라인이 불필요한 줄바꿈인것 같습니다.

2023-09-13 06:53 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        var = tl.load(var_ptr + pid)
143라인이 불필요한 줄바꿈인것 같습니다.

2023-09-13 06:53 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        )
블럭 포인터 선언 후 줄바꿈이 있으면 더 좋을 것 같습니다.

2023-09-13 06:53 UTC, daemyung commented on trident/kernel/batch_norm.py
> +
불필요한 줄바꿈인 것 같아요.

2023-09-13 07:14 UTC, ansteve commented on tests/test_batch_norm.py
> +        torch.nn.functional.batch_norm(input, running_mean=None, running_var=None, training=True),
`training` 파라미터의 정확한 용도를 잘 모르겠어서요.

2023-09-13 07:30 UTC, daemyung commented
@ansteve 그리고 커밋 제목이 조금 안맞는것 같아요. 기존의 구현이 잘못된 것인데 마치 3D 입력만 지원하지 않았던 것으로 이해되세요. 좋은 커밋 제목 없을까요?

2023-09-13 07:32 UTC, ansteve commented
> @ansteve 그리고 커밋 제목이 조금 안맞는것 같아요. 기존의 구현이 잘못된 것인데 마치 3D 입력만 지원하지 않았던 것으로 이해되세요. 좋은 커밋 제목 없을까요?

포괄적으로 `Fix BatchNorm` 으로 할까요?

2023-09-13 07:36 UTC, daemyung commented
> > @ansteve 그리고 커밋 제목이 조금 안맞는것 같아요. 기존의 구현이 잘못된 것인데 마치 3D 입력만 지원하지 않았던 것으로 이해되세요. 좋은 커밋 제목 없을까요?
> 
> 포괄적으로 `Fix BatchNorm` 으로 할까요?

음 그러면 `Fix bugs in BatchNorm`이 더 좋을 것 같아요.

2023-09-13 07:37 UTC, daemyung commented on tests/test_batch_norm.py
> +        torch.nn.functional.batch_norm(input, running_mean=None, running_var=None, training=True),
`instance_norm`의 `use_input_status`랑 동일한것 같은데요. 혹시 참고 해보시겠어요?

2023-09-13 08:39 UTC, ansteve commented on tests/test_batch_norm.py
> +        torch.nn.functional.batch_norm(input, running_mean=None, running_var=None, training=True),
`training`이 `track_running_stats`과 같은 뜻인거 같아요. 근데 `track_running_stats`와 `use_input_status`이 약간 다른 점이 BatchNorm에서는 `running_mean`, `running_var`를 인풋으로 사용하지 않고 단지 트랙킹 용으로만 사용하는 것 같습니다.

2023-09-13 08:48 UTC, ansteve commented on trident/function/function.py
> +    return operation.BatchNorm.apply(input, running_mean, running_var, weight, bias, momentum, eps)
이 변수를 밑단 까지 전달해주지 않아도 될거 같습니다. 밑단에서는 `running_mean`, `running_var`가 None인지 아닌지로 판단하면 될거 같습니다.

2023-09-13 08:50 UTC, ansteve commented on tests/test_batch_norm.py
> +def test_running_values(num_batches, y_size, x_size, device):
네 수정하겠습니다

2023-09-13 08:56 UTC, ansteve commented on trident/kernel/batch_norm.py
> +        tl.store(grad_input_block_ptr, grad_input, boundary_check=(0, 1))
`tl.store` 앞에 줄바꿈 있는게 좋은거 같습니다. 느낌상 `return` 앞에 줄바꿈 있는거처럼 다 끝나고 아웃풋 내보내는 느낌으로요.

2023-09-13 09:05 UTC, kakao-steve-ai commented on trident/kernel/batch_norm.py
> +
수정하겠습니다.

2023-09-13 09:05 UTC, kakao-steve-ai commented on trident/kernel/batch_norm.py
> +        var = tl.load(var_ptr + pid)
수정하겠습니다.

2023-09-13 09:05 UTC, kakao-steve-ai commented on trident/kernel/batch_norm.py
> +        )
수정하겠습니다.

2023-09-13 09:05 UTC, kakao-steve-ai commented on trident/kernel/batch_norm.py
> +        )
수정하겠습니다

2023-09-13 09:05 UTC, kakao-steve-ai commented on trident/kernel/batch_norm.py
> +
수정하겠습니다

2023-09-13 09:05 UTC, kakao-steve-ai commented on trident/kernel/batch_norm.py
> +
수정하겠습니다

2023-09-13 09:05 UTC, kakao-steve-ai commented on trident/kernel/batch_norm.py
> +        mean_ptr: tl.tensor,
수정하겠습니다

2023-09-13 09:05 UTC, kakao-steve-ai commented on trident/kernel/batch_norm.py
> +        y_size: tl.int32,
수정하겠습니다

2023-09-13 09:05 UTC, ansteve commented on trident/module.py
> +            self.running_var = torch.nn.Parameter(torch.empty(num_features, **factory_kwargs).fill_(1))
수정하겠습니다.

2023-09-13 09:05 UTC, ansteve commented on trident/operation/batch_norm.py
> +        eps: float,
이거는 코드 통일성 때문에 그런거죠? `float`과 `torch.float32`가 기능상 같은거죠?

2023-09-13 21:29 UTC, daemyung requested changes

2023-09-13 21:29 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        if running_mean_ptr is not None and running_var_ptr is not None:
`running_mean`과 `running_var`를 따로 처리해줄 수 있어요? 둘 중에 한개가 None이어도 처리가 되는게 맞다고 생각해요.

2023-09-14 01:16 UTC, ansteve commented on trident/kernel/batch_norm.py
> +        if running_mean_ptr is not None and running_var_ptr is not None:
수정하였습니다

2023-09-14 01:18 UTC, daemyung approved these changes
LGTM

2023-09-14 01:43 UTC, merged