Fix running_var of InstanceNorm
kakaobrain/trident pull request #125
Opened 2023-09-14 06:19 UTC by ansteve

## 🙏 Describe the pull request

* running_var 구할때는 correction 설정해서 구해야하는 것 같습니다. (분모 N이 아니라 N-1 이용.)
* N이 큰 값일때는 티가 안나지만 N이 작으면 테스트 실패합니다.

## ✅ Checklist

- [ ] Code follows the project's coding conventions and style.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated, if necessary.

2023-09-14 07:21 UTC, mejai1206 commented on trident/kernel/instance_norm.py
> +        running_var = var * (x_size / (x_size - 1)) * momentum + running_var * (1 - momentum)
`(x_size / (x_size - 1))` 가 빠졌던 때는 잘못된 동작이었던걸까요??

2023-09-14 07:28 UTC, ansteve commented on trident/kernel/instance_norm.py
> +        running_var = var * (x_size / (x_size - 1)) * momentum + running_var * (1 - momentum)
작은 사이즈에 대해 테스트해보면 pytorch랑 결과값이 다르게 나옵니다. 추측상 pytorch에서는 variance구할때 correction이 포함된 variance를 사용하는거 같습니다.

2023-09-14 07:34 UTC, mejai1206 commented on trident/kernel/instance_norm.py
> +        running_var = var * (x_size / (x_size - 1)) * momentum + running_var * (1 - momentum)
아 넵 `x_size`가 클수록 `(x_size / (x_size - 1))`가 작아져서 꽤 큰 입력에선 `(x_size / (x_size - 1))`가 없어도
테스트에서 안잡혔던 것이군요.

2023-09-14 07:34 UTC, mejai1206 approved these changes
LGTM

2023-09-14 09:43 UTC, daemyung requested changes
커밋 메세지가 명료하지 않은 것 같습니다. `Fix a bug in InstanceNorm not using input status` 어떠세요?

2023-09-14 09:43 UTC, daemyung commented on tests/test_instance_norm.py
> +    [(2, 8, 1024, True), (2, 2, 3, True), (2, 2, 2, True), (3, 5, 2000, False)],
테스트 `(2, 2, 3, True)`, `(2, 2, 2, True)` 모두 필요한가요?

2023-09-14 09:44 UTC, ansteve commented on tests/test_instance_norm.py
> +    [(2, 8, 1024, True), (2, 2, 3, True), (2, 2, 2, True), (3, 5, 2000, False)],
하나만 있어도 될거 같습니다. 하나는 지우겠습니다.

2023-09-14 09:44 UTC, ansteve commented
> 커밋 메세지가 명료하지 않은 것 같습니다. `Fix a bug in InstanceNorm not using input status` 어떠세요?

네 커밋 메시지 수정하겠습니다

2023-09-15 02:21 UTC, daemyung approved these changes
LGTM

2023-09-15 02:36 UTC, merged