Temp
kakaobrain/trident pull request #127
Opened 2023-09-14 10:38 UTC by ansteve

## 🙏 Describe the pull request

A clear and concise description of the pull request.

Resolves #

## 💬 Additional context

Add any other context or screenshots about the pull request here.

## ✅ Checklist

- [ ] Code follows the project's coding conventions and style.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated, if necessary.

2023-09-14 10:53 UTC, daemyung commented
@ansteve 이 PR에 `CUDA_VISIBLE_DEVICES: 2` 없애주는 패치 올려주세요.

2023-09-14 12:15 UTC, daemyung requested changes
`Update a workflow for tests`로 커밋 메세지 바꿔주시겠어요? 추후에 workflow가 여러개 생길 수 있어서 Github workflow는 적절하지 않아요.

2023-09-15 01:05 UTC, ansteve commented
> `Update a workflow for tests`로 커밋 메세지 바꿔주시겠어요? 추후에 workflow가 여러개 생길 수 있어서 Github workflow는 적절하지 않아요.

수정하였습니다

2023-09-15 01:06 UTC, daemyung approved these changes
LGTM

2023-09-15 01:09 UTC, mejai1206 approved these changes
LGTM

2023-09-15 01:33 UTC, merged