Implement optimizing root models
kakaobrain/trident pull request #153
Opened 2023-09-27 00:57 UTC by mejai1206

## 🙏 Describe the pull request
nn.Module 루트들을 찾아내서 교체하는 util을 추가하였습니다.

## 💬 Additional context
사용 예시 코드입니다.
```
skip_instances = (list, dict, set, torch.Tensor)
for key, value in pipe.components.items():
    trident.util.search_root_models_and_optimize(pipe, value, key, 0, skip_instances)
```

## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

2023-09-27 07:25 UTC, daemyung commented on trident/util/util.py
> +def search_root_models_and_optimize(parent, current, current_name, depth, skip_instances=None, max_depth=9):
이것을 optimize_model에서 할 수는 없나요? 따로 함수가 존재해야만 하나요?

2023-10-04 05:32 UTC, mejai1206 commented on trident/util/util.py
> +def search_root_models_and_optimize(parent, current, current_name, depth, skip_instances=None, max_depth=9):
`optimize_model` 은 `nn.Module`이 어딨는지 안다면 간편하고 빠르게 쓸 수 있고,
 `search_root_models_and_optimize`는 `nn.Module`을 직접 찾을 필요는 없지만 느려서 서로 쓰임새를 달리 할 수 있을 것 같아서 따로 두었습니다.
통합하도록 할까요?

2023-10-04 07:44 UTC, daemyung requested changes
쥬피터 노트북도 수정 부탁드려요.

2023-10-04 07:45 UTC, mejai1206 commented on trident/util/util.py
> +def search_root_models_and_optimize(parent, current, current_name, depth, skip_instances=None, max_depth=9):
optimize model function 을 삭제하는 것으로 PR 내용 수정하였습니다.

2023-10-04 07:57 UTC, daemyung approved these changes
LGTM

2023-10-04 07:58 UTC, ansteve approved these changes
LGTM

2023-10-04 08:02 UTC, merged