Implement BatchNorm Forward
kakaobrain/trident pull request #18
Opened 2023-07-06 01:08 UTC by ansteve

## 🙏 Describe the pull request

2D 인풋에 대한 BatchNorm의 forward 함수 구현했습니다

## ✅ Checklist

- [ ] Code follows the project's coding conventions and style.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated, if necessary.

2023-07-06 02:35 UTC, daemyung commented
@ansteve 역전파까지 구현하고 반영하죠.

2023-07-06 02:36 UTC, ansteve commented
> @ansteve 역전파까지 구현하고 반영하죠.

네 알겠습니다.

2023-07-06 02:39 UTC, daemyung requested changes

2023-07-06 02:39 UTC, daemyung commented on benchmarks/benchmark_batch_norm.py
> +        return triton.testing.do_bench(lambda: torch.nn.functional.batch_norm(inp, None, None, training=True))
`training`이 `True`여야하는 이유가 있나요?

2023-07-06 02:39 UTC, daemyung commented on tests/test_batch_norm.py
> +        torch.nn.functional.batch_norm(inp, None, None, training=True),
`torch.nn.functional.batch_norm(inp, None, None, training=True), trident.function.batch_norm(inp)`를 한 줄로 작성하면 PEP를 위배하나요?

2023-07-06 02:39 UTC, daemyung commented on trident/module.py
> +            device: the desired device of returned tensor
`device`와 `dtype`은 따로 주석을 달지 않으셔도 됩니다.

2023-07-06 02:39 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        std = triton.language.sqrt(var + eps)
`language.std`를 사용하시면 더 좋습니다.

2023-07-06 02:42 UTC, ansteve commented on benchmarks/benchmark_batch_norm.py
> +        return triton.testing.do_bench(lambda: torch.nn.functional.batch_norm(inp, None, None, training=True))
`training=False` 인 경우에, `running_mean`, `running_std`를 넣어주어야하는데 어떤 값을 넣어주어야 할지 몰라서 이렇게 했습니다. backward 쪽 구현하면서 좀 더 파악해보겠습니다.

2023-07-06 03:01 UTC, daemyung commented on benchmarks/benchmark_batch_norm.py
> +        return triton.testing.do_bench(lambda: torch.nn.functional.batch_norm(inp, None, None, training=True))
네~ 급하게 작업하지 않으셔도 됩니다. 완성도가 중요하니 천천히 잘 구현해 주세요.

2023-07-06 03:40 UTC, ansteve commented on tests/test_batch_norm.py
> +        torch.nn.functional.batch_norm(inp, None, None, training=True),
느낌상 긴 것 같아 줄 바꿈했는데 잘 모르겠네요.  [https://github.com/psf/black](black) 같은 파이썬 포맷터를 사용하는거 어떨까요? 전에 사용해봤는데 알아서 한줄로 바꿔주거나, 줄바꿈 해주거나 해서 편하더라고요.

2023-07-06 03:42 UTC, ansteve commented on trident/module.py
> +            device: the desired device of returned tensor
네 수정하겠습니다.

2023-07-06 03:42 UTC, ansteve commented on trident/kernel/batch_norm.py
> +        std = triton.language.sqrt(var + eps)
네 수정하겠습니다.

2023-07-06 04:00 UTC, daemyung commented on tests/test_batch_norm.py
> +        torch.nn.functional.batch_norm(inp, None, None, training=True),
좋습니다. 저는 PyCharm의 [Reformat Code](https://www.jetbrains.com/pycharm/guide/tips/reformat-code) 기능을 사용하고 있습니다.

2023-07-11 03:31 UTC, ansteve commented on benchmarks/benchmark_batch_norm.py
> +        return triton.testing.do_bench(lambda: torch.nn.functional.batch_norm(inp, None, None, training=True))
torch 쪽 테스트를 해보니까 `training=False`인 경우에는 `running_mean`, `running_var`을 인자로 받아서 이것을 mean, std 계산에 사용합니다. 이전에는 무조건 커널 내부에서 mean, std 계산하도록 했는데, 이 부분 torch 쪽이랑 작동 맞춰주기 위해서 수정하였습니다.

2023-07-11 04:39 UTC, daemyung requested changes

2023-07-11 04:39 UTC, daemyung commented on benchmarks/benchmark_batch_norm.py
> +@triton.testing.perf_report(
`util.report` 사용해 주세요.

2023-07-11 04:39 UTC, daemyung commented on benchmarks/benchmarker.py
> +    elif args.scenario == 'batch-norm':
`elif not args.scenario:`에도 `benchmark_batch_norm.run_benchmarks(args.mode, args.show_plots)` 추가해 주세요

2023-07-11 04:39 UTC, daemyung commented on benchmarks/benchmark_batch_norm.py
> +    elif mode == 'backward':
역전파도 구현하셨으니 역전파 벤치마크도 구현해주세요.

2023-07-11 04:39 UTC, daemyung commented on trident/function/function.py
> +    return operation.BatchNorm.apply(input, None, None, eps, None, None, running_mean, running_var)
`return` 전에 줄바꿈 있으면 더 좋을 것 같아요.

2023-07-11 04:39 UTC, daemyung commented on trident/kernel/batch_norm.py
> +        dxn = wgt * grad_out
`d` 대신에 `grad_`로 바꿔주세요. 저희 코드에서 미분값을 표현할때 `grad`를 사용합니다.

2023-07-11 04:39 UTC, daemyung commented on trident/module.py
> +        if affine:
`if-else` 시작과 후에 줄바꿈을 하는게 더 깔끔할 것 같아요.

2023-07-11 04:39 UTC, daemyung commented on trident/module.py
> +            self.weight = None
`None`의 경우 `self.register_parameter('weight', None)`로 초기화를 해야하더라고요.

2023-07-11 04:39 UTC, daemyung commented on trident/module.py
> +        if self.track_running_stats:
`if-else` 시작과 후에 줄바꿈을 하는게 더 깔끔할 것 같아요.

2023-07-11 06:07 UTC, daemyung commented
@ansteve 스타일 관련된 커멘트는 무시하세요. `black`을 사용할 예정입니다.

2023-07-11 06:08 UTC, ansteve commented
> @ansteve 스타일 관련된 커멘트는 무시하세요. `black`을 사용할 예정입니다.

네 알겠습니다~

2023-07-11 06:27 UTC, ansteve commented
@daemyung 코멘트 주신 것들 수정하였습니다.

2023-07-11 06:34 UTC, daemyung approved these changes
LGTM

2023-07-11 06:34 UTC, merged