Optimize Linear
kakaobrain/trident pull request #28
Opened 2023-07-12 07:19 UTC by mejai1206

## 🙏 Describe the pull request

- Linear의 순전파의 성능을 개선했습니다.
- Linear의 벤치마크를 정방 행렬(m=k=n)을 사용해서 측정하도록 수정하였습니다.
- Linear의 역전파를 구현했습니다.

## 💬 Additional context

`dot`의 `allow_tf32`와 `block pointer`를 사용하면 성능이 매우 집니다. 하지만 정밀도 차이가 발생하여 비활성화 합니다. 오차 허용을 증가(`atol=1e-1`)시키면 테스트에 통과합니다.

After:

![plot](https://github.com/kakaobrain/trident/assets/117069362/09277f9b-3053-49b5-87bb-3ae8fae3cc27)

Before:

![plot](https://github.com/kakaobrain/trident/assets/117069362/9129a0ea-d1e5-4587-a431-390caa9947de)

After with TF32:

![plot](https://github.com/kakaobrain/trident/assets/117069362/a41bd65b-5ba3-4cb8-ba8b-505f61e96d36)

## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

2023-07-12 08:16 UTC, ansteve commented on trident/kernel/linear.py
> +                                "blk_sz_m": 64,
잘몰라서 질문드리는데, blk_sz_m은 고정하는 이유가 있나요?

2023-07-12 08:32 UTC, mejai1206 commented on trident/kernel/linear.py
> +                                "blk_sz_m": 64,
특별한 이유는 없고, 
5중 for문까지는 너무 가독성이 좋진 않을까해서 고정해두긴 했습니다. 
m을 튜닝했을 때도 유의미한 성능 향상이 있는지 확인 해보고. 필요하다면 추가 하는 것도 좋겠군요

2023-07-12 08:52 UTC, daemyung commented on benchmarks/util.py
> +def make_benchmark_multi_values(title, x_names, x_vals, args):
함수를 추가하지말고 `make_benchmark`를 수정하는게 더 좋을것 같습니다.

2023-07-12 08:52 UTC, daemyung commented on benchmarks/benchmark_linear.py
> +    "linear forward", ["m", "k", "n"], [256 * i for i in range(1, 15)], {}
`m`, `n`, `k`가 모두 동일한 값을 가지는데 다른 값으로 지정할 수 있나요?

2023-07-12 08:52 UTC, daemyung commented on benchmarks/benchmark_linear.py
> +)
`args`가 사용되지 않는 경우가 `{}`를 넘기는데 이것보다는 `report`에서 기본 인자 값을 설정하는게 더 좋을것 같습니다.

2023-07-12 08:52 UTC, daemyung commented on tests/test_linear.py
> +def test_function_with_bias(num_bt, inp_feat, out_feat, device):
`test_function_with_bias`를 `test_function`과 합쳐주세요.

2023-07-12 08:52 UTC, daemyung commented on tests/util.py
> +def train_with_activation(inp, tgt, mod, act, crit=torch.nn.MSELoss()):
`train`함수에 `act`기능을 추가해주세요.

2023-07-12 08:52 UTC, daemyung commented on trident/operation/linear.py
> +    def __activation_grad(act, out):
`__activation_grad`를 따로 함수로 빼지 말고 `__backward`에 구현해주세요.

2023-07-12 08:52 UTC, daemyung commented on trident/operation/linear.py
> +    def __backward(grad_out, inp, wgt, out, act):
이 구현을 `kernel.Linear.backward`로 옮겨주세요. `operation`에선 기능 구현을 하지 않습니다.

2023-07-12 08:52 UTC, daemyung commented on trident/operation/linear.py
> +        if bis is None:
이 분기문은 필요 없어 보입니다. 함수 호출시 두 경우를 처리할 수 있는 것으로 생각됩니다.

2023-07-12 08:52 UTC, daemyung commented on trident/operation/linear.py
> +        inp, wgt, _, act = inputs
`_`로 받지 말고 `bis`로 받으세요.

2023-07-12 08:52 UTC, daemyung commented on trident/module.py
> +            torch.empty(out_features, in_features, device="cuda")
`weight`가 없으면 `self.register_parameter("weight", None)` 이렇게 처리해주세요.

2023-07-12 08:52 UTC, daemyung commented on trident/kernel/linear.py
> +    x_block_ptr = tl.make_block_ptr(
`import triton.language as tl` 삭제하시고 `triton.language`로 풀어서 써주세요.

2023-07-12 08:52 UTC, daemyung commented on trident/kernel/linear.py
> +    total = tl.zeros((blk_sz_m, blk_sz_n), dtype=tl.float32)
이런 경우에 `total`말고 `acc`를 사용한답니다.

2023-07-12 08:52 UTC, daemyung commented on trident/kernel/linear.py
> +        base=w_ptr,
`base, shape, strides, offsets, block_shape, order`가 순서대로 정의되었다면 변수를 바로 넘겨주세요.

2023-07-12 08:53 UTC, daemyung commented
@mejai1206 "Optimize Linear"가 PR과 Commit 제목으로 적절해 보입니다.

2023-07-12 09:21 UTC, mejai1206 commented on benchmarks/benchmark_linear.py
> +    "linear forward", ["m", "k", "n"], [256 * i for i in range(1, 15)], {}
음.. 되지 않는 것 같습니다.
차라리 기존처럼 하나의 값 `k`만 받고.
`bench_linear_forward` 안에서 `n = m =k` 이렇게 할당하는 것이 더 좋을까요?

2023-07-12 09:24 UTC, daemyung commented on benchmarks/benchmark_linear.py
> +    "linear forward", ["m", "k", "n"], [256 * i for i in range(1, 15)], {}
아뇨 `util.report` 함수가 `list`를 받도록 변경하시죠.

2023-07-12 10:36 UTC, mejai1206 commented on trident/module.py
> +            torch.empty(out_features, in_features, device="cuda")
weight는 in_features, out_features를 통해 항상 만들어서

bias와 activation에 대해서 아래와 같이 처리하겠습니다.
```
        if bias:
            self.bias = torch.nn.Parameter(torch.empty(out_features, device="cuda"))
        else:
            self.register_parameter("bias", None)

        if activation is not None:
            self.activation = activation
        else:
            self.register_parameter("activation", None)
```

2023-07-13 04:03 UTC, daemyung requested changes

2023-07-13 04:03 UTC, daemyung commented on tests/util.py
> +def train(inp, tgt, mod, crit=torch.nn.MSELoss(), act=None):
파라미터의 순서가 `act`가 `crit`보다 먼저 오는게 적절할 것 같아요. 왜냐하면 `act`를 수행한 뒤에 에러를 계산하니까요.

2023-07-13 04:03 UTC, daemyung commented on trident/kernel/linear.py
> +        x_ptr,
줄여도 한줄이 안되는군요. 미안한데 가독성을 위해서 필요한 부분만 다시 파라미터 이름 넣어줄래요?

2023-07-13 04:03 UTC, daemyung commented on trident/kernel/linear.py
> +    for k in range(0, sz_k, blk_sz_k):
`for`문 전에 한줄 띄어주세요.

2023-07-13 04:03 UTC, daemyung commented on trident/kernel/linear.py
88번째 줄은 삭제 부탁드려요.

2023-07-13 04:03 UTC, daemyung commented on trident/kernel/linear.py
> +        range_n = triton.language.arange(0, blk_sz_n) + j * blk_sz_n
이 코드 `language.block`으로 대체할 수 있을것 같습니다.

2023-07-13 04:03 UTC, daemyung commented on trident/module.py
> +            torch.empty(out_features, in_features, device="cuda")
activation은 훈련이 필요 없는 파라미터라서 `register_parameter`말고 기존처럼 할당해 주세요.

2023-07-13 04:03 UTC, daemyung commented on trident/module.py
> +        return operation.Linear.apply(input, self.weight, self.bias, self.activation)
`function.linear`로 호출해 주세요.

2023-07-13 05:22 UTC, mejai1206 commented on trident/module.py
> +        return operation.Linear.apply(input, self.weight, self.bias, self.activation)
네 그럼 test도  `test_function`과 `test_forward`가 있는중인데 
`test_forward`로 대체 하도록하겠습니다.

2023-07-13 07:16 UTC, daemyung requested changes

2023-07-13 07:16 UTC, daemyung commented on tests/test_linear.py
> +    "act, num_bt, inp_feat, out_feat",
이 경우는 인풋 관련된 변수 후에 액티베이션이 나오면 더 좋을 것 같아요.

2023-07-13 07:16 UTC, daemyung commented on trident/kernel/linear.py
> +import triton.language
`import triton.language` 삭제해 주세요.

2023-07-13 23:00 UTC, daemyung requested changes

2023-07-13 23:00 UTC, daemyung commented on trident/operation/linear.py
> +        if bis is None:
이 부분 수정해 주세요.

2023-07-14 05:01 UTC, mejai1206 commented on trident/operation/linear.py
> +    def __backward(grad_out, inp, wgt, out, act):
넵 커널로 작성을 해야한다는 것이죠?
현재는 두번의 커널 호출하는 방식으로 하면 금방될 것 같긴한데..
기왕이면 한번의 커널 호출로 해보고 싶은데 현재 아이디어가 잘 떠오르지 않아서 일단은 토치 구현으로 뒀는데
두번의 커널 형태로라도 구현 해두는게 좋을까요?

2023-07-14 05:03 UTC, daemyung commented on trident/operation/linear.py
> +    def __backward(grad_out, inp, wgt, out, act):
아니요 커널로 작성할 필요 없이 지금 구현을 `kernel.Linear.backward`로 옮겨달라는거에요. 여기서는 호출만 하고요.

2023-07-14 05:06 UTC, mejai1206 commented on trident/operation/linear.py
> +    def __backward(grad_out, inp, wgt, out, act):
아 네넵 알겠습니다

2023-07-14 05:20 UTC, daemyung requested changes

2023-07-14 05:20 UTC, daemyung commented on trident/kernel/linear.py
> +        def activation_grad(act, out):
내장 함수를 없애고 그냥 바로 계산하는게 더 보기 편하지 않나요?

2023-07-14 05:20 UTC, daemyung commented on trident/kernel/linear.py
> +
줄바꿈이 불필요해 보입니다.

2023-07-14 05:22 UTC, mejai1206 commented on trident/kernel/linear.py
> +        def activation_grad(act, out):
음.. 그게 낫겠군요

2023-07-14 05:45 UTC, daemyung approved these changes
LGTM

2023-07-14 05:48 UTC, ansteve approved these changes
좋아보입니다.

2023-07-14 05:51 UTC, merged

2023-07-14 05:51 UTC, daemyung commented
@mejai1206 PR 설명 수정했습니다. 확인 부탁드려요.

2023-07-14 05:53 UTC, mejai1206 commented
네  설명 좋은 것 같습니다.
감사합니다.