Implement Linear backward
kakaobrain/trident pull request #34
Opened 2023-07-25 04:46 UTC by mejai1206

## 🙏 Describe the pull request

Linear 의 역전파를 커널로 구현하였습니다.

## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

2023-07-25 05:13 UTC, ansteve reviewed
제가 잘 몰라서 그런데, kernel 함수를 2개로 (backward_activation_bias, backward_matrix)로 분리한 이유가 있을까요? CUDA에서는 커널 함수가 디폴트 스트림을 사용하면 병렬적으로 수행될 수 없는데, 여기서는 어떤지 잘 모르겠네요.

2023-07-25 05:43 UTC, mejai1206 commented
@ansteve
backward_activation_bias와 backward_matrix 분리한 배경에 대해서는 아래 2가지 이유 때문에 분리하였습니다.

1. activation 계산 중복
되도록이면 backward_matrix 에서 모든걸 해결하고자 했었습니다.
backward_matrix내에서 행렬곱 계산하는 부분에서 grad_ou t을 로드하고
activation을 적용후 행렬곱을 하려고 했더니 activation 계산이 중복되는게 보여서 2단계로 나누는게 좋겠다고 생각이 되었습니다.
backward_activation_bias에서 중복없이 element당 단 한번의 activation을 적용하고 다음 절차로 보내주게 되었습니다.

2. grad_bias 계산시 atomic_add 피하기
backward_matrix의 (blk_sz_m, blk_sz_k)의 형태에선
grad_bis를 위한 sum을 저장하는 과정에서 atomic_add를 사용할 수 밖에 없게 되었습니다.
다른 형태로 블럭을 구성할시엔 grad_bis에 atomic_add를 피할 수 있었습니다.

그래서 1,2를 함께 해결하기 위해서 backward_activation_bias를 두게 되었습니다.

일단 이런 이유로 이렇게 하였는데

더 좋은 방법이 있었으면 좋겠네요!

2023-07-25 23:11 UTC, daemyung requested changes

2023-07-25 23:11 UTC, daemyung commented on tests/test_linear.py
> +        (12, 34, 3, "relu"),
테스트가 중복된 것 같습니다. `act`마다 하나씩 있어도 충분합니다.

2023-07-25 23:11 UTC, daemyung commented on trident/kernel/linear.py
> +                grad_act *= triton.language.where(
Activation의 역전파를 각각 구현하지 마시고 `ReLU.backward`를 호출해 주세요.

2023-07-25 23:11 UTC, daemyung commented on trident/kernel/linear.py
> +    def backward_activation_bias(
`backward_bias`가 더 적절해 보입니다. Activation은 `act`로 표현되니까요.

2023-07-25 23:11 UTC, daemyung commented on trident/kernel/linear.py
> +    def backward_matrix(
위의 함수의 이름과 통일성을 고려하면 `backward_input_weight`가 더 적절합니다.

2023-07-25 23:11 UTC, daemyung commented on trident/operation/linear.py
> +        def grid_act_bis(meta):
`grid`로 함수 이름 바꿔주세요.

2023-07-25 23:11 UTC, daemyung commented on trident/operation/linear.py
> +        def grid_mat(meta):
`grid`로 함수 이름 바꿔주세요.

2023-07-25 23:11 UTC, daemyung commented on trident/kernel/linear.py
> +        dtype: triton.language.constexpr,
`dtype`이 제일 마지막에 오도록 변경해주세요. PyTorch와 통일성을 유지하기 위해서입니다.

2023-07-25 23:11 UTC, daemyung commented on trident/kernel/linear.py
> +        dtype: triton.language.constexpr,
`dtype`이 제일 마지막에 오도록 변경해주세요. PyTorch와 통일성을 유지하기 위해서입니다.

2023-07-25 23:11 UTC, daemyung commented on trident/operation/linear.py
> +        y = torch.empty((m, n), device=inp.get_device(), dtype=inp.dtype)
함수 초입에 `ctor_args = {"device": inp.device, "dtype": inp.dtype}`로 선언하고 텐서를 생성할때 재활용하세요.

2023-07-25 23:12 UTC, daemyung commented
@ansteve @mejai1206 간단한 연산들은 `backward` 하나로 구현이 되었지만 복잡한 연산들은 `backward_xxx`, `backward_yyy`와 같이 여러 함수가 필요합니다. 함수의 이름 규칙을 어떻게 정하는게 좋을까요?

2023-07-26 03:51 UTC, mejai1206 commented
@daemyung 
음... backward_ XXX에서 XXX는 계산의 결과를 대표하는 이름을 적는것 정도가 생각납니다.

2023-07-26 04:01 UTC, mejai1206 commented on trident/kernel/linear.py
> +                grad_act *= triton.language.where(
Activation을 하면서 함께 grad_bias계산도 병행하면 좋을 것 같은데
이럴 경우엔  ReLU.backward에 익스텐션처럼 추가하는게 좋을까요?

2023-07-26 04:02 UTC, daemyung commented
@mejai1206 @ansteve input의 역전파를 계산하는 커널은 `backward`라고하고 그 외의 커널들은 변수 이름을 붙일까요? 예를 들면 `backward_bias`처럼요. 여러개의 미분 값을 출력할때는 `and`를 붙일까요? 아니면 붙이지 말까요?

2023-07-26 04:04 UTC, mejai1206 commented
@mejai1206 @ansteve  
음.. 개인적으론 and 없이 _ 로도 구분해도 좋을 것 같습니다.

2023-07-26 04:05 UTC, ansteve commented
@daemyung 좋은 생각인거 같습니다. 저도 개인적으로 `and` 없는게 더 좋은거 같습니다.

2023-07-26 04:05 UTC, daemyung commented
@ansteve @mejai1206 `and`는 붙이지 말죠.

2023-07-26 05:57 UTC, daemyung commented
@ansteve `GroupNorm`에서 가끔씩 테스트 실패하는데요?

2023-07-26 05:59 UTC, ansteve commented
> @ansteve `GroupNorm`에서 가끔씩 테스트 실패하는데요?

원인 분석 해보겠습니다.

2023-07-26 07:11 UTC, daemyung commented
@mejai1206 PR과 커밋의 제목을 "Optimize Linear"로 변경하는게 좋을 것 같습니다. 왜냐하면 기존에도 역전파가 지원되었기 때문이죠. 커밋 본문에 "역전파를 커널로 구현했다."를 명세하면 좋을 것 같습니다.

2023-07-26 07:15 UTC, daemyung approved these changes
LGTM

2023-07-26 07:15 UTC, daemyung commented on trident/kernel/linear.py
> +                grad_act *= triton.language.where(
`ReLU.backward`를 CUDA의 디바이스 함수처럼 사용하라는 의미였습니다. 그런데 코드를 자세히 적용할 수 없겠네요. 기존 구현 유지하시죠.

2023-07-26 07:18 UTC, ansteve approved these changes
LGTM

2023-07-26 07:19 UTC, daemyung requested changes

2023-07-26 07:19 UTC, daemyung commented on trident/kernel/linear.py
> +    def backward_input_weight(
@mejai1206 `input`의 역전파인 경우에는 `bacward`로 이름 짓기로 하지 않았나요?

2023-07-26 07:26 UTC, mejai1206 commented on trident/kernel/linear.py
> +    def backward_input_weight(
아 네 input의 grad만을 계산할 경우는 `backward` 로 하고
이 커널은 weight의 grad도 같이 계산하니까 `backward_weight`로 변경하면 좋을까요?

2023-07-26 07:32 UTC, daemyung commented on trident/kernel/linear.py
> +    def backward_input_weight(
아뇨 input의 계산이 포함되는 경우는 `backward`로 하고 `input`과 같이 계산되지 않는 애들은 `backward_xxx`로 하죠.

2023-07-26 07:37 UTC, mejai1206 commented on trident/kernel/linear.py
> +    def backward_input_weight(
넵 `backward` 로 변경하였습니다.

2023-07-26 07:40 UTC, daemyung approved these changes
LGTM

2023-07-26 07:46 UTC, merged