Optimize PReLU
kakaobrain/trident pull request #40
Opened 2023-08-02 11:32 UTC by mejai1206

## 🙏 Describe the pull request

PReLU를 최적화하였습니다.

## 💬 Additional context
a30 기준 벤치마크 변화입니다.

After
<img width="280" alt="after" src="https://github.com/kakaobrain/trident/assets/117069362/12ae09a4-5184-4c3a-a0b9-e9d9a0d6a00f">

Befroe
<img width="280" alt="before" src="https://github.com/kakaobrain/trident/assets/117069362/0a0dc368-2c27-4d93-aae7-b4757f5cb9b2">

## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

2023-08-02 23:45 UTC, daemyung requested changes
고생하셨습니다. 커멘트 검토 후 반영하실만한 내용은 반영해 주세요.

2023-08-02 23:45 UTC, daemyung commented on benchmarks/benchmark_prelu.py
> +    "prelu forward", ["vec_size"], [256 * i for i in range(1, 21)], {"num_batches": 16}
[PyTorch](https://pytorch.org/docs/stable/generated/torch.nn.InstanceNorm1d.html#torch.nn.InstanceNorm1d)는 2차원의 경우 `num_batches`, `vec_size`보다는 `num_channels`, `length`라고 부르더군요. 저희도 이러한 맥락을 따르는게 좋다고 생각합니다. 아니면 `num_rows`, `num_columns`도 좋다고 생각합니다.

2023-08-02 23:45 UTC, daemyung commented on benchmarks/benchmark_prelu.py
> +    input = torch.randn(num_batches, vec_size, device="cuda")
`device`, `dtype`의 경우는 `factory_kwargs = {"device": device, "dtype": dtype"}`으로 넘겨주세요.

2023-08-02 23:45 UTC, daemyung commented on benchmarks/benchmark_prelu.py
> +        lyr = torch.nn.PReLU(vec_size, 0.3, device="cuda")
`lyr`라는 약어 말고 `operation`을 사용해 주세요.

2023-08-02 23:45 UTC, daemyung commented on benchmarks/benchmark_prelu.py
> +    out = lyr.forward(input)
`out`도 `output`으로 바꿔주세요.

2023-08-02 23:45 UTC, daemyung commented on tests/test_prelu.py
> +    "num_batches, vec_size", [(512, 512), (200, 300), (100, 1), (1, 100)]
`benchmark_prelu.py`에서 언급한대로 변수명 변경해 주세요.

2023-08-02 23:45 UTC, daemyung commented on trident/kernel/prelu.py
> +        num_cols,
`num_cols`를 `num_columns`로 변경해 주세요.

2023-08-02 23:45 UTC, daemyung commented on trident/kernel/prelu.py
> +        output_ptr,
커널에서 값이 써지는 `output_ptr`을 1번째 파라미터로 옮겨주세요. 이렇게 변경하고자 하는 이유는 커널의 경우 값을 반환할 수 없기 때문에 입니다. 이러한 제약사항이 있는 경우에 대부분의 API들이 출력 변수부터 선언하더라고요.

2023-08-02 23:45 UTC, daemyung commented on trident/kernel/prelu.py
> +            triton.Config(
Config의 구성이 중구난방인것 같은데 값에 따른 정렬을 해줄 수 있나요?

2023-08-02 23:45 UTC, daemyung commented on trident/kernel/prelu.py
> +        block_size_m: triton.language.constexpr,
`block_size_m`의 변수 이름은 부적절해 보입니다. `m_block_size`가 더 좋은 것 같습니다. 왜냐하면 변수 이름을 만들때 중요한 개념부터 먼저 나오는게 좋습니다. 이 경우에 `m`이 중요한 단어기 때문에 `block_size_m` 보다는 `m_block_size`가 의미전달이 더 잘됩니다.

2023-08-02 23:45 UTC, daemyung commented on trident/kernel/prelu.py
> +        block_size_n: triton.language.constexpr,
`n_block_size`로 변경해 주세요.

2023-08-02 23:45 UTC, daemyung commented on trident/kernel/prelu.py
> +            base=input_ptr,
`base`는 표시하지 않아도 충분한 의미 전달이 된다고 생각합니다. `base`를 명시하지 말고 바로 포인터 넘겨주세요.

2023-08-02 23:45 UTC, daemyung commented on trident/kernel/prelu.py
> +    @triton.autotune(
순전파의 커멘트를 참고해서 역전파도 수정해 주세요.

2023-08-02 23:45 UTC, daemyung commented on trident/operation/prelu.py
> +                triton.cdiv(num_batches, meta["block_size_m"]),
2차원 그리드가 더 좋은가요? 만약 2차원 그리드가 더 좋다면 주가 되는 축을 0차원에 정의해 주세요.

2023-08-02 23:45 UTC, daemyung commented on trident/operation/prelu.py
> +        num_batches, vec_size = input.shape
`num_rows`, `num_columns` 또는 `num_channels`, `length`로 변경해 주세요.

2023-08-02 23:45 UTC, daemyung commented on trident/operation/prelu.py
> +        return grad_output * grad_input, grad_output * grad_weight, None
곱셈 연산을 `backward` 커널에서 할 수 있을것 같은데요?

2023-08-03 02:46 UTC, mejai1206 commented on trident/kernel/prelu.py
> +            triton.Config(
backward와 중복 제거겸 다음과 같이 조합 되도록 변경하겠습니다.

```
def autotune_configs():
    configs = []

    for m_block_size in [32, 64, 128]:
        for n_block_size in [32, 64, 128]:
            for num_stages in [4, 5]:
                for num_warps in [4, 8, 16]:
                    configs.append(
                        triton.Config(
                            {
                                "m_block_size": m_block_size,
                                "n_block_size": n_block_size,
                            },
                            num_stages=num_stages,
                            num_warps=num_warps,
                        )
                    )

    return configs
````

2023-08-03 05:33 UTC, mejai1206 commented on trident/operation/prelu.py
> +                triton.cdiv(num_batches, meta["block_size_m"]),
1차원이 조금 더 성능이 좋네요. 
1차원으로 수정하도록 하겠습니다.

2023-08-03 05:34 UTC, mejai1206 commented on trident/operation/prelu.py
> +        return grad_output * grad_input, grad_output * grad_weight, None
아.. 잊고 있었는데, 적용하니까 backward 성능이 많이 개선되서 torch보다 좋네요.

2023-08-03 06:46 UTC, daemyung requested changes

2023-08-03 06:46 UTC, daemyung commented on benchmarks/benchmark_prelu.py
> +    "prelu forward", ["num_columns"], [256 * i for i in range(1, 21)], {"num_rows": 16}
`num_rows`는 `y_size`로 `num_columns`는 `x_size`로 새로 정한 이름 규칙에 맞게 바꿔주세요.

2023-08-03 06:46 UTC, daemyung commented on trident/kernel/prelu.py
> +def autotune_configs():
함수 이름이 `configs`가 더 좋을 것 같아요. `autotune`은 해당 함수와는 관련이 없어요.

2023-08-03 06:46 UTC, daemyung commented on trident/operation/prelu.py
> +                triton.cdiv(num_rows, meta["m_block_size"])
Tuple로 반환해 주세요. `(x, )` 이렇게요.

2023-08-03 06:46 UTC, daemyung commented on trident/kernel/prelu.py
> +        program_id = triton.language.program_id(0)
`pid`로 변경해 주세요.

2023-08-03 06:46 UTC, daemyung commented on trident/kernel/prelu.py
> +        column_idx = language.cdiv(num_columns, n_block_size)
`column_idx`보다 `num_column_blocks`가 더 적절할 것 같아요.

2023-08-03 06:46 UTC, daemyung commented on tests/test_prelu.py
> +def test_backward(num_rows, num_columns, device):
`dtype`도 추가해 주세요.

2023-08-03 07:05 UTC, daemyung commented on trident/kernel/prelu.py
> +def autotune_configs():
아니면 configs_for_autotune?

2023-08-03 07:09 UTC, daemyung commented on trident/kernel/prelu.py
> +def autotune_configs():
아니면 `all_configs`?

2023-08-07 06:36 UTC, ansteve commented on trident/kernel/prelu.py
> +        j = program_id % column_idx
블록 포인터를 사용하는 경우에는 2차원 pid를 사용하는 것보다 이렇게 1차원 pid를 사용하고 i, j를 구하는 방식이 더 일반적인가요? 속도 측면에서 이게 더 좋은가요?

2023-08-07 07:37 UTC, mejai1206 commented on trident/kernel/prelu.py
> +        j = program_id % column_idx
`0`번째 축은 갯수 제한이 없기도 하고
또 벤치마크를 돌려보니 1차원이 미세하게 더 빨라서 이 방법을 택하게 되었습니다.

2023-08-07 07:42 UTC, daemyung commented on trident/kernel/prelu.py
> +        j = program_id % column_idx
@ansteve 일반적인 경우에도 1차원을 사용합니다. `i`, `j`를 구하는 비용은 매우 쌉니다. CUDA로 `grid`를 변경하면서 테스트를 해보면 `grid`의 `x`, `y`을 바꾸는것만으로도 성능에 차이가 발생합니다.

2023-08-07 08:46 UTC, mejai1206 commented on trident/kernel/prelu.py
> +        column_idx = language.cdiv(num_columns, n_block_size)
`column` 대신 `x`를 쓰기로 했으니 `num_x_blocks` 로 변경하도록 하겠습니다.

2023-08-07 10:35 UTC, ansteve approved these changes
LGTM

2023-08-07 23:04 UTC, daemyung approved these changes
LGTM

2023-08-07 23:04 UTC, merged