Implement Attention
kakaobrain/trident pull request #45
Opened 2023-08-08 02:55 UTC by ansteve

## 🙏 Describe the pull request

* Attention forward 구현입니다.
* IS_CAUSAL 관련 에러 확인중입니다.
* Test 에러 확인중입니다.

## 💬 Additional context
<img width="592" alt="스크린샷 2023-08-07 오후 7 36 13" src="https://github.com/kakaobrain/trident/assets/9404329/38a801fe-a461-40c4-9aaf-df7e141ede44">

## ✅ Checklist

- [ ] Code follows the project's coding conventions and style.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated, if necessary.

2023-08-22 02:14 UTC, daemyung requested changes

2023-08-22 02:14 UTC, daemyung commented on benchmarks/benchmark_attention.py
> +    num_batches, num_heads, d_head = 4, 48, 64
`d_head`가 입력 단어의 크기 아니였나요? `embedding_size`, `output_size`, `word_size`가 더 적절하지 않을까요?

2023-08-22 02:14 UTC, daemyung commented on benchmarks/benchmark_attention.py
> +    q = torch.randn((num_batches, num_heads, x_size, d_head), **factory_kwargs)
`query`, `key`, `value`라고 쓸 필요가 없을까요? 어텐션에서 `q`, `k`, `v`가 흔히 쓰이는 표현이라서 고민이 되네요.

2023-08-22 02:14 UTC, daemyung commented on trident/function/function.py
> +    sm_scale = 1.0 / math.sqrt(k.shape[-1])
인라인 처리하는게 더 보기 좋을 것 같습니다. 또 `sm_scale`보다는 `softmax_scale`을 사용하는게 가독성에 더 좋을것 같습니다.

2023-08-22 02:14 UTC, daemyung commented on tests/test_attention.py
> +def test_forward(is_causal, embed_size, device):
`embed_size`보다 `embedding_size`가 더 적절한 것 같습니다.

2023-08-22 02:14 UTC, daemyung commented on tests/test_attention.py
> +    query = torch.rand(6, 9, 1024, embed_size, **factory_kwargs)
텐서 생성에 쓰이는 값들을 변수화 했으면 좋겠습니다. 예를 들면 `num_batches`, `num_heads`, `word_size`, `embedding_size`, 더 좋은 단어가 있으면 그걸로 사용해 주세요.

2023-08-22 02:14 UTC, daemyung commented on trident/kernel/attention.py
> +        stride_qh: tl.constexpr,
변수명을 정할때 중요한 것 부터 먼저오는게 좋습니다. `stride_qh`의 경우 `qh`가 `stride`보다 더 중요하다고 생각이 됩니다. 그래서 `qh_stride`가 더 적절하다고 생각합니다.

2023-08-22 02:14 UTC, daemyung commented on trident/kernel/attention.py
> +        output: tl.tensor,
변수명이 `output_ptr`이여야 할 것 같습니다.

2023-08-22 02:14 UTC, daemyung commented on trident/kernel/attention.py
> +        logsumexp: tl.tensor,
띄어쓰기 부탁드려요.

2023-08-22 02:14 UTC, daemyung commented on trident/kernel/attention.py
> +        Q: tl.tensor,
대문자 말고 소문자 사용 부탁드려요.

2023-08-22 02:33 UTC, ansteve commented on tests/test_attention.py
> +    query = torch.rand(6, 9, 1024, embed_size, **factory_kwargs)
`num_batches`, `num_heads`, `sequence_size`, `embedding_size` 로 수정하겠습니다.

2023-08-22 02:33 UTC, ansteve commented on benchmarks/benchmark_attention.py
> +    num_batches, num_heads, d_head = 4, 48, 64
`num_batches`, `num_heads`, `sequence_size`, `embedding_size` 로 수정하겠습니다.

2023-08-22 02:36 UTC, ansteve commented on benchmarks/benchmark_attention.py
> +    q = torch.randn((num_batches, num_heads, x_size, d_head), **factory_kwargs)
`key`가 reserved keyword 여서 그런지, `key`라는 변수명을 쓰면 triton에서 에러가 발생합니다. 그래서 `q`, `k`, `v`를 사용했습니다.

2023-08-22 02:50 UTC, daemyung commented on benchmarks/benchmark_attention.py
> +    q = torch.randn((num_batches, num_heads, x_size, d_head), **factory_kwargs)
그런데 여기는 Python이라서 상관 없을것 같은걸요?

2023-08-22 02:51 UTC, mejai1206 commented on trident/function/function.py
> +    assert len(q.size()) == 4
`q`가 4여야 하는 이유가 궁금한데 혹시 알 수 있을까요?

2023-08-22 02:53 UTC, ansteve commented on benchmarks/benchmark_attention.py
> +    q = torch.randn((num_batches, num_heads, x_size, d_head), **factory_kwargs)
네 파이썬 쪽에서는 `query`, `key`, `value` 로 써도 되는거 같습니다. 한번 바꿔보겠습니다.

2023-08-22 02:54 UTC, mejai1206 commented on trident/kernel/attention.py
> +        off_hz = tl.program_id(1)
`off_*` 인 것들은 `offest_*` 으로 바뀌면 좋을 것 같습니다.

2023-08-22 02:56 UTC, ansteve commented on trident/function/function.py
> +    assert len(q.size()) == 4
커널 함수가 인풋이 4차원이라고 가정하고, `stride(0)`, `stride(1)`, `stride(2)`, `stride(3)` 을 받아서 사용하고 있어서요. 여러 차원을 지원하려면 커널 쪽 코드가 바뀌어야해서 일단은 4차원을 강제했습니다.

2023-08-22 02:57 UTC, mejai1206 commented on trident/kernel/attention.py
> +        qk_scale = sm_scale * 1.44269504
`1.44269504` 가 log_2(e) 의 의미를 가진 상수 변수로 바꾸는 것 괜찮을까요?

2023-08-22 03:00 UTC, ansteve commented on trident/kernel/attention.py
> +        qk_scale = sm_scale * 1.44269504
네 `log_2_of_e` 라는 변수로 수정하겠습니다

2023-08-22 03:00 UTC, mejai1206 commented on trident/function/function.py
> +def scaled_dot_product_attention(q, k, v, dropout_p=0.0, is_causal=False, use_accelerator=False):
타입을 명시하기로 했으므로, 파라미터들의 타입이 명시되면 좋을 것 같습니다.

2023-08-22 03:05 UTC, mejai1206 commented on trident/kernel/attention.py
> +        q = tl.load(query_block_ptr)
혹시 `tl.load()`시 boundary_check는 필요하진 않는지 궁금합니다. 
`m_block_size`와 `m_block_size`가 항상 나누어 떨어지는게 보장 되어서 없는 것일까요?

2023-08-22 04:36 UTC, ansteve commented on trident/function/function.py
> +    sm_scale = 1.0 / math.sqrt(k.shape[-1])
수정했습니다

2023-08-22 04:36 UTC, ansteve commented on trident/kernel/attention.py
> +        stride_qh: tl.constexpr,
수정했습니다

2023-08-22 04:39 UTC, ansteve commented on trident/kernel/attention.py
> +        q = tl.load(query_block_ptr)
넣는게 좋을거 같네요. 수정하겠습니다.

2023-08-22 07:42 UTC, daemyung requested changes

2023-08-22 07:42 UTC, daemyung commented on tests/test_attention.py
> +    def bwd(func):
여기도 기존 테스트 코드처럼 변경해주시겠어요?

2023-08-22 07:45 UTC, ansteve commented on tests/test_attention.py
> +    def bwd(func):
`bwd`를 `train`으로 변경하는거 말씀하시는거죠?

2023-08-22 08:02 UTC, daemyung commented on tests/test_attention.py
> +    def bwd(func):
넵!

2023-08-22 10:17 UTC, daemyung requested changes

2023-08-22 10:17 UTC, daemyung commented on tests/test_attention.py
> +        func(q, k, v, is_causal=is_causal).backward(grad_out, retain_graph=True)
`is_causal=is_causal` 대신에 `is_causal`만 넘길 수 없나요?

2023-08-22 10:17 UTC, daemyung commented on trident/function/function.py
> +def scaled_dot_product_attention(
PyTorch의 [scaled_dot_product_attention](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html)과 인터페이스가 다른데 통일할 수 없나요?

2023-08-22 10:17 UTC, daemyung commented on trident/kernel/attention.py
> +            base=q_ptr + qvk_offset,
`base=`는 명시하지 않습니다.

2023-08-22 10:17 UTC, daemyung commented on trident/kernel/attention.py
> +        # initialize offsets
불필요한 주석들은 제거해주세요.

2023-08-22 10:17 UTC, daemyung commented on trident/kernel/attention.py
> +        q_ptr: tl.tensor,
reserved keyword가 아니면 `query_ptr`처럼 변수명을 다 써줬으면 좋겠습니다.

2023-08-22 10:17 UTC, daemyung commented on trident/language/constant.py
> +
불필요한 줄바꿈입니다.

2023-08-22 10:17 UTC, daemyung commented on trident/language/constant.py
> +log_2_of_e = tl.constexpr(1.44269504)
`e`를 상수로 등록하시고 `tl.math.log2`를 사용하세요.

2023-08-22 10:17 UTC, daemyung commented on trident/operation/attention.py
> +        Lq, Lk, Lv = query.shape[-1], key.shape[-1], value.shape[-1]
대문자로 선언된 변수를 풀어써주세요.

2023-08-22 10:17 UTC, daemyung commented on trident/operation/attention.py
> +    def forward(ctx, query, key, value, is_causal, softmax_scale, use_accelerator):
파라미터 타입 명시해주세요.

2023-08-22 10:17 UTC, daemyung commented on trident/kernel/attention.py
> +        log_sum_exp_ptr: tl.tensor,
`log_sum_exp`보다 `delta` 같은 심볼을 사용할 수 없을까요?

2023-08-23 03:44 UTC, ansteve commented on trident/kernel/attention.py
> +        log_sum_exp_ptr: tl.tensor,
FlashAttention2 논문에 logsumexp L 이라고 쓰여있어서 다른 심볼이 생각이 안나네요.

2023-08-23 03:47 UTC, ansteve commented on trident/function/function.py
> +def scaled_dot_product_attention(
`attn_mask`, `dropout_p`는 아직 구현이 안되어서 제거하겠습니다. 그러면 나머지는 인터페이스 동일합니다.(use_accelerator가 추가적으로 있는것 빼고는)

2023-08-23 03:48 UTC, ansteve commented on tests/test_attention.py
> +        func(q, k, v, is_causal=is_causal).backward(grad_out, retain_graph=True)
`is_causal` 로만 넘기겠습니다

2023-08-23 04:50 UTC, ansteve commented on tests/test_attention.py
> +        func(q, k, v, is_causal=is_causal).backward(grad_out, retain_graph=True)
`attn_mask`, `dropout_p`, `is_causal` 중에 무엇인지 명시가 되어야 해서 `is_causal=is_causal` 로 넘겨야하네요.

2023-08-23 05:53 UTC, daemyung commented on trident/function/function.py
> +def scaled_dot_product_attention(
알겠습니다.

2023-08-23 05:58 UTC, daemyung requested changes

2023-08-23 05:58 UTC, daemyung commented on trident/operation/attention.py
> +        # shape constraints
불필요한 주석인것 같습니다.

2023-08-23 05:58 UTC, daemyung commented on trident/operation/attention.py
> +        output = torch.empty_like(query)
`assert` 다음에 한 줄 띄어주세요.

2023-08-23 05:58 UTC, daemyung commented on trident/operation/attention.py
> +        z, h, y, x = output.shape
`num_batches`, `num_heads`, `y_size`, `x_size`가 되어야할 것 같습니다.

2023-08-23 05:58 UTC, daemyung commented on trident/kernel/attention.py
> +        acc = tl.zeros([m_block_size, embedding_size], dtype=tl.float32)
`sum`이나 `accumulation`이 좋을 것 같습니다.

2023-08-23 06:16 UTC, ansteve commented on trident/operation/attention.py
> +        z, h, y, x = output.shape
수정하였습니다.

2023-08-23 06:17 UTC, ansteve commented on trident/kernel/attention.py
> +        acc = tl.zeros([m_block_size, embedding_size], dtype=tl.float32)
수정하였습니다.

2023-08-23 07:09 UTC, daemyung approved these changes
LGTM

2023-08-23 07:10 UTC, merged