Implement Online Variance
kakaobrain/trident pull request #46
Opened 2023-08-08 09:07 UTC by ansteve

## 🙏 Describe the pull request

A clear and concise description of the pull request.

Resolves #

## 💬 Additional context

Add any other context or screenshots about the pull request here.

## ✅ Checklist

- [ ] Code follows the project's coding conventions and style.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated, if necessary.

2023-08-09 01:26 UTC, ansteve commented
<img width="581" alt="스크린샷 2023-08-09 오전 10 23 07" src="https://github.com/kakaobrain/trident/assets/9404329/af435506-97ab-48cc-b401-3886265c9f7b">
<img width="584" alt="스크린샷 2023-08-09 오전 10 22 31" src="https://github.com/kakaobrain/trident/assets/9404329/71377933-21a8-4d59-8593-5c83f36bd3e6">
(그래프에서 torch는 기존 Variance, trident는 Online Variance 입니다) 
블록 사이즈를 줄이는 경우 Online Variance가 기존 Variance보다 더 빨라지는 것을 확인할 수 있었습니다.
하지만 기존 Variance도 mean을 인풋으로 넣어주면 최적화가 되기 때문에 이 경우에는 기존 Variance가 빨랐습니다.

2023-08-09 03:15 UTC, mejai1206 approved these changes
LGTM

2023-08-09 04:43 UTC, daemyung commented on trident/language/language.py
> +        m2 = triton.language.zeros((1, block_size), triton.language.float32)
m2가 뭐에요?

2023-08-09 04:46 UTC, ansteve commented on trident/language/language.py
> +        m2 = triton.language.zeros((1, block_size), triton.language.float32)
여기 위키의 수학공식에 나오는 M2 라는 변수인데, 노션에 수학공식에 대한 설명 정리하겠습니다. https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Welford's_online_algorithm

2023-08-09 04:48 UTC, ansteve commented on trident/language/language.py
> +        m2 = triton.language.zeros((1, block_size), triton.language.float32)
M2는 분산에 n-1을 곱한 값이라고 보시면 됩니다. 마지막에 M2를 n-1으로 나누면 분산이 됩니다.

2023-08-09 04:49 UTC, daemyung commented on trident/language/language.py
> +        count = triton.language.zeros((1, block_size), triton.language.float32)
`var`안에 넣는 대신에 `online_var`거나 `fast_var` 함수로 따로 빼는것은 어떨까요?

2023-08-09 04:54 UTC, ansteve commented on trident/language/language.py
> +        count = triton.language.zeros((1, block_size), triton.language.float32)
다른 함수로 분리하는 이유가 개발자가 `var`를 쓸지 `online_var`를 쓸지 고를 수 있게 하기 위해서인가요?

2023-08-09 05:05 UTC, daemyung commented on trident/language/language.py
> +        count = triton.language.zeros((1, block_size), triton.language.float32)
네 그것도 그렇고 `var` 안에서 `fast_var`를 따로 호출하는게 가독성 측면에서 더 좋을것 같아요.

2023-08-09 05:06 UTC, ansteve commented on trident/language/language.py
> +        count = triton.language.zeros((1, block_size), triton.language.float32)
네 알겠습니다. 분리하겠습니다.

2023-08-09 06:06 UTC, daemyung commented on trident/language/language.py
> +def _m2_combine(m2_a, mean_a, count_a, m2_b, mean_b, count_b):
함수 이름을 좀 더 직관적으로 바꿀 수 없을까요?

2023-08-09 07:17 UTC, ansteve commented on trident/language/language.py
> +def _m2_combine(m2_a, mean_a, count_a, m2_b, mean_b, count_b):
어떤 이름이 좋을까요? combine을 사용했던 이유는 triton에서 대부분 reduce함수에 combine이라 이름을 쓰더라고요. https://github.com/openai/triton/blob/main/python/triton/language/core.py#L1517

2023-08-10 01:48 UTC, daemyung requested changes

2023-08-10 01:48 UTC, daemyung commented on trident/language/function.py
> +    count = triton.language.zeros((1, block_size), triton.language.float32)
`count`가 `(1, block_size)`으로 생성될 필요가 있어요? `scalar`나 `(1, 1)`로 생성되도 될 것 같아요.

2023-08-10 01:48 UTC, daemyung commented on trident/language/function.py
> +def _m2_combine(m2_a, mean_a, count_a, m2_b, mean_b, count_b):
이 함수를 `fast_var` 안에서 선언할 수 있어요?

2023-08-10 01:48 UTC, daemyung commented on trident/language/function.py
> +def fast_var(
`online_var`보다 `fast_var`가 더 적절한 이름이라고 생각하시는거죠?

2023-08-10 01:48 UTC, daemyung commented on trident/language/function.py
> +
아래 `var` 함수는 항상 `mean`을 받도록 수정하는게 좋을 것 같아요. 지금은 `mean`이 없으면 계산해주는데 이걸 삭제하는게 더 바람직해 보여요.

2023-08-10 01:48 UTC, daemyung commented on trident/operation/var.py
> +            util.block_size(size_along_dim, 4 * input.element_size()),
`num_warps`처럼 `correction` 변수를 넣어서 `block_size`를 결정하도록 하는게 좋을 것 같습니다.

2023-08-10 01:51 UTC, daemyung commented
@ansteve 커밋 메세지의 제목을 다음과 같이 변경하면 좋을 것 같아요.

```
Optimize Var with Welford's online algorithm
```

2023-08-10 05:08 UTC, ansteve commented on trident/language/function.py
> +def _m2_combine(m2_a, mean_a, count_a, m2_b, mean_b, count_b):
함수 안에서 함수 정의하려고 하니까 triton compile 에러가 발생하네요. triton에서 지원하지 않는 기능인것 같습니다.

2023-08-10 05:08 UTC, ansteve commented on trident/language/function.py
> +def fast_var(
네 `fast_var`가 더 적절한거 같습니다.

2023-08-10 05:08 UTC, ansteve commented on trident/language/function.py
> +    count = triton.language.zeros((1, block_size), triton.language.float32)
라인 305에 reduce 할때 count 배열도 필요해서 생성이 필요해보입니다.

2023-08-10 05:08 UTC, ansteve commented on trident/language/function.py
> +
네 수정하겠습니다.

2023-08-10 05:08 UTC, ansteve commented on trident/operation/var.py
> +            util.block_size(size_along_dim, 4 * input.element_size()),
네 수정하겠습니다.

2023-08-10 05:24 UTC, ansteve commented
> @ansteve 커밋 메세지의 제목을 다음과 같이 변경하면 좋을 것 같아요.
> 
> ```
> Optimize Var with Welford's online algorithm
> ```

커밋 메시지 수정하였습니다.

2023-08-10 06:09 UTC, daemyung requested changes

2023-08-10 06:09 UTC, daemyung commented on trident/language/function.py
> +    count = triton.language.zeros((1, block_size), triton.language.float32)
네 알겠습니다.

2023-08-10 06:09 UTC, daemyung commented on trident/language/function.py
> -    if average is None:
`average` 변수명을 `mean`으로 바꿔주실 수 있을까요?

2023-08-10 06:09 UTC, daemyung commented on trident/language/function.py
> +def _fast_var_m2_combine(m2_a, mean_a, count_a, m2_b, mean_b, count_b):
함수 이름으로 `combine_welford`가 더 적절한 것 같아요.

2023-08-10 06:09 UTC, daemyung commented on trident/language/function.py
> +def _fast_var_m2_combine(m2_a, mean_a, count_a, m2_b, mean_b, count_b):
`a`, `b`로 그룹화 하는 것 보다 `set1`, `set2`로 그룹화 하는건 별로인가요?

2023-08-10 06:09 UTC, daemyung commented on trident/language/function.py
> +        m2_a + m2_b + pow2(mean_b - mean_a) * count_a * count_b / (count_a + count_b),
3개를 반환해야하는 이유가 있나요?

2023-08-10 06:10 UTC, daemyung commented on trident/language/function.py
> +def _fast_var_m2_combine(m2_a, mean_a, count_a, m2_b, mean_b, count_b):
이러한 함수들이 많이 생길 것 같은데 `combine.py`로 따로 분류해서 관리해도 좋을 것 같습니다.

2023-08-10 06:27 UTC, ansteve commented on trident/language/function.py
> +def _fast_var_m2_combine(m2_a, mean_a, count_a, m2_b, mean_b, count_b):
`set1`, `set2` 보다 `a`, `b` 가 더 좋은거 같습니다. 더 짧기도 하고, 2개 그룹만 있기 때문입니다.

2023-08-10 06:27 UTC, ansteve commented on trident/language/function.py
> +def _fast_var_m2_combine(m2_a, mean_a, count_a, m2_b, mean_b, count_b):
네 파일 분리하고 이름 수정하겠습니다.

2023-08-10 06:27 UTC, ansteve commented on trident/language/function.py
> -    if average is None:
네 수정하겠습니다

2023-08-10 06:27 UTC, ansteve commented on trident/language/function.py
> +        m2_a + m2_b + pow2(mean_b - mean_a) * count_a * count_b / (count_a + count_b),
이 함수는 한번만 호출되는게 아니라 reduce 과정에서 계속해서 호출되면서 값을 병합해 갑니다. 병합의 중간 과정에서도 3개 값이 다 필요하기 때문에 3개를 반환합니다.

2023-08-10 06:33 UTC, daemyung commented on trident/language/function.py
> +def _fast_var_m2_combine(m2_a, mean_a, count_a, m2_b, mean_b, count_b):
네 알겠습니다.

2023-08-10 06:33 UTC, daemyung commented on trident/language/function.py
> +        m2_a + m2_b + pow2(mean_b - mean_a) * count_a * count_b / (count_a + count_b),
알겠습니다.

2023-08-10 07:05 UTC, daemyung approved these changes
LGTM, 고생 많으셨습니다. `reduce` 세미나 부탁드려요.

2023-08-10 07:05 UTC, merged

2023-08-10 07:09 UTC, ansteve commented
> LGTM, 고생 많으셨습니다. `reduce` 세미나 부탁드려요.

다음주 중에 reduce 세미나 진행하겠습니다.