Implement CosineSimilarity
kakaobrain/trident pull request #48
Opened 2023-08-10 07:32 UTC by mejai1206

## 🙏 Describe the pull request

CosineSimilarity 를 구현했습니다.

## 💬 Additional context
측정 기기: a30

순전파
<img width="280" alt="순전파" src="https://github.com/kakaobrain/trident/assets/117069362/855a0595-338b-4706-b717-43e7d149e8b6">

역전파
<img width="280" alt="역전파" src="https://github.com/kakaobrain/trident/assets/117069362/48b35821-de2f-4653-b9bc-4ae9bb8d1760">

## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

2023-08-10 09:15 UTC, daemyung requested changes

2023-08-10 09:15 UTC, daemyung commented on benchmarks/benchmark_cosine_similarity.py
> +    input1 = torch.randn(z_size, y_size, x_size, **factory_kwargs)
변수명 `input`, `other`가 더 적절해 보입니다.

2023-08-10 09:15 UTC, daemyung commented on benchmarks/benchmark_cosine_similarity.py
> +    "cosine_similarity backward",
타이틀에는 `_`을 사용하지 않습니다. `cosine_similarity`로 변경해 주세요.

2023-08-10 09:15 UTC, daemyung commented on benchmarks/benchmark_cosine_similarity.py
> +    "cosine_similarity forward",
타이틀에는 `_`을 사용하지 않습니다. `cosine_similarity`로 변경해 주세요.

2023-08-10 09:15 UTC, daemyung commented on benchmarks/benchmark_cosine_similarity.py
> +    {"z_size": 16, "y_size": 16},
`z_size`는 배치인가요?

2023-08-10 09:15 UTC, daemyung commented on tests/test_cosine_similarity.py
> +    input1 = torch.randn(z_size, y_size, x_size, **factory_kwargs)
변수명 `input`, `other`가 더 적절해 보입니다.

2023-08-10 09:15 UTC, daemyung commented on trident/function/function.py
> +def consine_similarity(input1, input2, dim=1, eps=1e-08):
함수를 설명하는 주석을 달아주세요.

2023-08-10 09:15 UTC, daemyung commented on trident/language/function.py
> +def grad_sqrt(x):
역전파 관련된 함수는 함수로 만들지 말아주세요.

2023-08-10 09:15 UTC, daemyung commented on trident/module.py
> +    def __init__(self, dim: int = 1, eps: float = 1e-8):
저희는 아규먼트의 타입을 정의하지 않습니다.

2023-08-10 09:15 UTC, daemyung commented on trident/module.py
> +        Applies Cosine similarity to inputs.
Cosine을 cosine으로 변경해 주세요.

2023-08-10 09:15 UTC, daemyung commented on trident/module.py
> +    def forward(self, input1, input2):
PyTorch 문서에는 변수명이 `x1`, `x2`로 되어 있긴 하네요.

2023-08-10 09:15 UTC, daemyung commented on trident/module.py
> +        return operation.CosineSimilarity.apply(input1, input2, self.dim, self.eps)
`operation`에서 호출하지 말고 `function`을 호출해 주세요.

2023-08-10 09:26 UTC, ansteve commented on trident/module.py
> +    def __init__(self, dim: int = 1, eps: float = 1e-8):
코딩스타일 관련 얘기인거 같은데, 나중에 한번 회의 해보면 좋을 것 같아요. 저는 개인적으로 아규먼트 타입 넣어주는게 버그도 줄여주고 좋은것 같아서요.

2023-08-10 09:34 UTC, mejai1206 commented on benchmarks/benchmark_cosine_similarity.py
> +    "cosine_similarity forward",
`cosine similarity forward` 이렇게 변경하겠습니다.

2023-08-10 09:36 UTC, mejai1206 commented on benchmarks/benchmark_cosine_similarity.py
> +    {"z_size": 16, "y_size": 16},
가장 외부의 차원인데, 배치일지 어떻게 사용할지에 달린 것 같습니다.
`sum` 과 비슷하다고 생각하여 z, y, x 로 이름 지었습니다.

2023-08-10 09:42 UTC, mejai1206 commented on benchmarks/benchmark_cosine_similarity.py
> +    input1 = torch.randn(z_size, y_size, x_size, **factory_kwargs)
변경하겠습니다.

2023-08-10 09:59 UTC, mejai1206 commented on trident/module.py
> +        return operation.CosineSimilarity.apply(input1, input2, self.dim, self.eps)
변경하겠습니다.

2023-08-10 10:02 UTC, mejai1206 commented on trident/module.py
> +    def forward(self, input1, input2):
`x1`, `x2` 변경하겠습니다.

2023-08-10 10:07 UTC, daemyung commented on benchmarks/benchmark_cosine_similarity.py
> +    {"z_size": 16, "y_size": 16},
흠 코드를 작성하다보니 배치를 축으로 나타내면 코드를 작성하다가 헷갈리더라고요. 채널까진 괜찮은데,,,

2023-08-10 10:07 UTC, daemyung commented on trident/module.py
> +    def __init__(self, dim: int = 1, eps: float = 1e-8):
내일 티타임 시간에 이야기 하시죠.

2023-08-10 10:09 UTC, mejai1206 commented on trident/language/function.py
> +def grad_sqrt(x):
`grad_sqrt `  `grad_reciprocal` 삭제하겠습니다.

2023-08-10 10:12 UTC, mejai1206 commented on benchmarks/benchmark_cosine_similarity.py
> +    {"z_size": 16, "y_size": 16},
음.. 그럼 가장 외부차원인 `z_size` 만 `num_batches`라 바꾸고, 나머지 `y_size`, `x_size` 는 그대로 쓰는게 좋을까요?

2023-08-11 01:57 UTC, mejai1206 commented on benchmarks/benchmark_cosine_similarity.py
> +    {"z_size": 16, "y_size": 16},
논의결과대로 `z_size` --> `num_batches` 변경하겠습니다.

2023-08-11 04:40 UTC, daemyung requested changes
`triton.language`를 `tl`로 바꿔주세요.

2023-08-11 04:51 UTC, mejai1206 commented
cosine_similarity, language/constant, language/function
이부분 `tl` 로 수정되었습니다.

2023-08-11 04:54 UTC, daemyung requested changes

2023-08-11 04:54 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +        input1_ptr,
`x1_ptr`, `x2_ptr`로 바꿔주세요.

2023-08-11 04:54 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +            ).to(tl.float32)
`float32`로 형변환을 하지 않으면 계산 결과가 틀리나요?

2023-08-11 04:54 UTC, daemyung commented on trident/operation/cosine_similarity.py
> +    def __forward(ctx, input1, input2, dim, eps):
`x1`, `x2`로 바꿔주세요.

2023-08-11 05:02 UTC, mejai1206 commented on trident/kernel/cosine_similarity.py
> +        input1_ptr,
변경하겠습니다.

2023-08-11 05:10 UTC, mejai1206 commented on trident/kernel/cosine_similarity.py
> +            ).to(tl.float32)
순전파 커널에선 `x1`, `x2` 로드시 `to(tl.float32)` 를 하지 않아도 테스트를 통과하는군요.
이부분에서의 형변환은 생략 하도록 하겠습니다.

2023-08-11 05:27 UTC, daemyung commented
만든 PR이 반영되기 전에 다른 PR들이 반영되면 저는 다음 방법으로 히스토리를 정리합니다.

1. 현재 커밋의 ID를 복사합니다.
2. `git reset --hard HEAD~1`
3. `git pull origin main`
4. `git cherry-pick {복사한 커밋 ID}`
5. `git push origin {브랜치 이름} --force`

2023-08-11 05:28 UTC, mejai1206 commented on trident/kernel/cosine_similarity.py
> +            ).to(tl.float32)
역전파의
```
            denominator = tl.load(denominator_block_ptr).to(tl.float32)
            numerator = tl.load(numerator_block_ptr).to(tl.float32)
            grad_output = tl.load(grad_output_block_ptr).to(tl.float32)
```       
여기도 형변환 빼도 통과해서 추가로 삭제했습니다.

2023-08-11 05:28 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +
불필요한 줄바꿈으로 보입니다.

2023-08-11 05:33 UTC, mejai1206 commented
위 방법은 main 최신을 기반으로 리베이스한 것과 히스토리 결과가 다른걸까요?

2023-08-11 05:35 UTC, daemyung commented
> 위 방법은 main 최신을 기반으로 리베이스한 것과 히스토리 결과가 다른걸까요?

무슨 말인지 이해를 못했어요. 저 방법이 최신 main을 기반으로 리베이스하는 거에요.

2023-08-11 05:38 UTC, ansteve commented on trident/kernel/cosine_similarity.py
> +                order=(2, 1, 0),
order를 어떻게 지정하는지에 따라 속도차이가 있나요?

2023-08-11 05:42 UTC, ansteve commented on trident/kernel/cosine_similarity.py
> +        if dim == language.dim[0]:
여기 if, elif, else에서 겹치는 코드가 많은거 같은데, 혹시 `shape`, `strides`만 앞에서 따로 계산하는거는 어떤가요?

2023-08-11 05:48 UTC, mejai1206 commented
main 최신 기반으로 충돌 제거하여 리베이스했습니다.

2023-08-11 05:52 UTC, mejai1206 commented on trident/kernel/cosine_similarity.py
> +                order=(2, 1, 0),
a30기준 벤치마크상으론 크게 변하는건 없었습니다만,
차원의 순서에 대한 order를 지정하는건, 특정 하드웨어에서 더 나은 성능을 주는데 도움이 된다고 적혀 있긴 했었습니다.

(참고: https://triton-lang.org/main/getting-started/tutorials/08-experimental-block-pointer.html )

Note that the order argument is set to (1, 0), which means the second axis is the inner dimension in terms of storage, and the first axis is the outer dimension. This information may sound redundant, but it is necessary for some hardware backends to optimize for better performance.

2023-08-11 05:55 UTC, mejai1206 commented on trident/kernel/cosine_similarity.py
> +        if dim == language.dim[0]:
`shape` `strides` 를 먼저 결정하고
이후에 `block_pointer` 를 만들고 싶었으나, 그렇게하면 트리톤의 버그인지 컴파일 에러가 나고,
아직 더 나은 방법을 못찾아서 일단 이렇게 하였습니다.

2023-08-11 05:55 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +        if dim == language.dim[0]:
@ansteve 컴파일러가 죽어요.

2023-08-11 05:56 UTC, ansteve commented on trident/kernel/cosine_similarity.py
> +        if dim == language.dim[0]:
넵 알겠습니다.

2023-08-11 05:57 UTC, ansteve approved these changes
LGTM

2023-08-11 05:59 UTC, daemyung approved these changes
LGTM

2023-08-11 05:59 UTC, merged

2023-08-11 08:00 UTC, daemyung commented on trident/kernel/cosine_similarity.py
> +                order=(2, 1, 0),
@ansteve `row-major`, `column-major` 정도로 이해하고 있습니다.