Optimize Softmax Backward
kakaobrain/trident pull request #58
Opened 2023-08-17 00:24 UTC by ansteve

## 🙏 Describe the pull request

* 큰 벡터의 경우 Backward 안되던 문제 해결했습니다.
* 메모리 많이 사용하는 diagonal 행렬 대신 메모리 효율적인 방법을 사용했습니다. 
* dim=0, 1 지원하도록 수정했습니다.

## ✅ Checklist

- [ ] Code follows the project's coding conventions and style.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated, if necessary.

2023-08-17 01:48 UTC, daemyung commented
@ansteve 고생하셨습니다. 커밋 메세지를 다음 중에서 마음에 드는걸로 변경해주실 수 있을까요?

1. backward의 첫 글자를 소문자로 변경했습니다.
```
Optimize Softmax backward
```

2. backward를 강조, 하지만 1번이 더 깔끔합니다.
```
Optimize the backward of Softmax
```

3. 메모리 사용량 최적화를 강조합니다.
```
Optimize memory usage of Softmax
    
Only tensors of small sizes were able to be backpropagated.
```

2023-08-17 01:59 UTC, ansteve commented
> @ansteve 고생하셨습니다. 커밋 메세지를 다음 중에서 마음에 드는걸로 변경해주실 수 있을까요?
> 

3번으로 수정했습니다. 감사합니다.

2023-08-17 02:02 UTC, mejai1206 commented on tests/test_softmax.py
>      ctor_args = {"device": device, "dtype": dtype}
변수명을 풀어쓰기로 한 뒤로는
`ctor_args` 대신 `factory_kwargs` 로 쓰이는 코드가 자주 보이는데, `factory_kwargs`로의 변경 괜찮을까요?

2023-08-17 02:03 UTC, ansteve commented on tests/test_softmax.py
>      ctor_args = {"device": device, "dtype": dtype}
factory_kwargs 로 변경하겠습니다.

2023-08-17 02:11 UTC, mejai1206 commented on tests/test_softmax.py
> +    inp = torch.randn(y_size, x_size, **factory_kwargs)
`inp` 와 `tgt`를  풀어서 쓰는 것 괜찮을까요?

2023-08-17 02:12 UTC, ansteve commented on tests/test_softmax.py
> +    inp = torch.randn(y_size, x_size, **factory_kwargs)
수정하겠습니다

2023-08-17 02:25 UTC, mejai1206 approved these changes
LGTM

2023-08-17 02:25 UTC, mejai1206 commented on trident/operation/softmax.py
> +        if dim == 0:
티타임에서 얘기주신  `dim`에 따른 `block_pointer` 생성 분기를 없애주신 방법은 여기인걸까요?

2023-08-17 02:27 UTC, ansteve commented on trident/operation/softmax.py
> +        if dim == 0:
네 이런식으로 하면 커널에서 분기를 없앨 수 있습니다. 분기가 없어지는 대신 약간 머릿속이 복잡해지는 것 같고, 어떤게 더 좋을지 모르겠네요.

2023-08-17 02:28 UTC, mejai1206 commented on trident/operation/softmax.py
> +        if dim == 0:
아 넵 전 이 방법 좋은 것 같습니다~

2023-08-17 03:00 UTC, daemyung requested changes

2023-08-17 03:00 UTC, daemyung commented on trident/kernel/softmax.py
> +def configs_for_softmax():
`configs`로도 충분하다고 생각합니다.

2023-08-17 03:00 UTC, daemyung commented on trident/operation/softmax.py
> +            stride_0 = 1
이런 경우에 `size_along_dim`이라는 변수 이름을 사용하고 있습니다. 다른 `stride_1`은 항상 1이니까 선언하지 않고요. 그리고 이 계산을 커널 안으로 옮기는게 더 좋을 것 같습니다.

2023-08-17 03:00 UTC, daemyung commented on trident/operation/softmax.py
> +        delta = torch.empty(y_size, dtype=torch.float32, device="cuda")
`delta` 생성시 `factory_kwrags = {"device" = grad_output.device, "dtype" = grad_output.dtype"}`을 정의하고 생성해 주세요.

2023-08-17 03:00 UTC, daemyung commented on trident/kernel/softmax.py
> +    def backward_preprocess(
`backward_delta`로 이름 변경 제안드립니다. `input`의 역전파를 제외하고는 `backward_{변수이름}`으로 함수 이름을 만들 고 있습니다.

2023-08-17 04:36 UTC, ansteve commented on trident/kernel/softmax.py
> +def configs_for_softmax():
`trident/kernel/__init__.py` 에서 `import *` 를 해주고 있어서, 나중에 다른 파일에 있는 `configs`와 이름 충돌이 생길까봐 이렇게 했습니다. 어떻게 하는게 좋을까요?

2023-08-17 04:38 UTC, ansteve commented on trident/kernel/softmax.py
> +def configs_for_softmax():
이름을 `configs` 로 바꾸고 `Softmax` 클래스 안쪽으로 이동시키면 되겠네요.

2023-08-17 04:40 UTC, daemyung commented on trident/kernel/softmax.py
> +def configs_for_softmax():
이름 충돌이 생겨도 어짜피 `Softmax`만 사용하는 거라 상관 없다고 생각합니다. 클래스 안으로 정의하는 것은 안되더라고요?

2023-08-17 05:02 UTC, ansteve commented on trident/operation/softmax.py
> +        delta = torch.empty(y_size, dtype=torch.float32, device="cuda")
중간 계산 과정에서는 `float32`를 사용하고 있어서, 굳이 `grad_output.dtype` 정의해서 변환하는 것이 불필요해보였습니다. `factory_kwargs`는 변경하겠습니다.

2023-08-17 05:02 UTC, ansteve commented on trident/kernel/softmax.py
> +    def backward_preprocess(
이름 수정하겠습니다

2023-08-17 05:04 UTC, daemyung commented on trident/operation/softmax.py
> +        delta = torch.empty(y_size, dtype=torch.float32, device="cuda")
아하! 그런 이유라면 dtype이 필요 없어보입니다.

2023-08-17 05:18 UTC, ansteve commented on trident/operation/softmax.py
> +            stride_0 = 1
`x_size`, `y_size`를 커널에 넘겨주기 보다 `size_along_dim`, `size_against_dim`라는 이름으로 넘겨주는게 좋아보이네요. `size_against_dim`라는 이름 괜찮아보이시나요?

2023-08-17 05:40 UTC, ansteve commented on trident/kernel/softmax.py
> +def configs_for_softmax():
클래스 안으로 넣는거 되는거 같습니다.

2023-08-17 05:52 UTC, ansteve commented on trident/operation/softmax.py
> +            stride_0 = 1
커널 안에서 `strides = (1, size_against_dim) if dim == 0 else (size_along_dim, 1)` 이런식으로 변수 선언하니까 컴파일 에러가 발생해서 일단 stride_0, stride_1 라는 변수 유지했습니다.

2023-08-17 06:39 UTC, daemyung requested changes

2023-08-17 06:39 UTC, daemyung commented on trident/kernel/softmax.py
> +        delta_ptr: tl.tensor,
리턴값을 아웃 파라미터로 정의하는 경우에 리턴값부터 아규먼트로 선언됩니다. `delta_ptr`을 제일 앞으로 옮겨주세요.

2023-08-17 06:39 UTC, daemyung commented on trident/operation/softmax.py
> +            stride_0 = 1
@ansteve 이름 좋습니다.

2023-08-17 06:39 UTC, daemyung commented on trident/kernel/softmax.py
> +            stride_1 = size_against_dim
`size_against_dim`, `size_along_dim`을 내부적으로 계산하면 안되는 건가요?

2023-08-17 06:39 UTC, daemyung commented on trident/kernel/softmax.py
> +        delta = tl.zeros((1,), tl.float32)
최적화가 필요해 보입니다.
1. delta를 block_size의 크기로 선언해주세요.

2023-08-17 06:39 UTC, daemyung commented on trident/kernel/softmax.py
> +            delta += tl.sum(output * grad_output, axis=1)
최적화 연속 커멘트입니다.
2. `delta += output * grad_output`로 더해주세요.

2023-08-17 06:39 UTC, daemyung commented on trident/kernel/softmax.py
> +            output_block_ptr = tl.advance(output_block_ptr, (0, block_size))
최적화 연속 커멘트입니다.
3. `delta = tl.sum(delta, 1)`로 최종 delta를 구해주세요.

이렇게 하면 Reduce 횟수를 줄일 수 있습니다.

2023-08-17 06:48 UTC, ansteve commented on trident/operation/softmax.py
> +            return (size_against_dim,)
> `size_against_dim`, `size_along_dim`을 내부적으로 계산하면 안되는 건가요?

여기와 아래 line 71에서 사용하고 싶어서 커널 외부에서 설정했습니다.

2023-08-17 06:49 UTC, ansteve commented on trident/kernel/softmax.py
> +            output_block_ptr = tl.advance(output_block_ptr, (0, block_size))
아하 수정하겠습니다.

2023-08-17 07:50 UTC, daemyung commented on trident/operation/softmax.py
> +            return (size_against_dim,)
아 네, 제 말은 `size_against_dim`, `size_along_dim`을 커널로 넘기지 말고 커널에서 다시 구해주는게 어떠냐는 의미였어요.

2023-08-17 07:55 UTC, kakao-steve-ai commented on trident/operation/softmax.py
> +            return (size_against_dim,)
아 그런뜻이었군요. 외부에서 이미 구했으니 넘겨주는것도 나쁘지 않은거 같습니다.

2023-08-17 07:56 UTC, daemyung commented on trident/operation/softmax.py
> +            return (size_against_dim,)
내부에서 계산해 주시겠어요? 커널에 파라미터를 많이 넘기는게 성능상으로 좋지 않거든요.

2023-08-17 07:58 UTC, kakao-steve-ai commented on trident/operation/softmax.py
> +            return (size_against_dim,)
넵

2023-08-17 08:05 UTC, kakao-steve-ai commented on trident/operation/softmax.py
> +            return (size_against_dim,)
커널 안에서는 `output.shape`를 가져올 수가 없네요. 결국 `x_size`, `y_size `를 넘겨주거나 `size_against_dim`, `size_along_dim` 를 넘겨주어야하는데, 이렇게 되면 커널에 넘겨줘야하는 파라미터 개수는 똑같아서 그대로 둬도 괜찮을거 같습니다.

2023-08-17 08:08 UTC, daemyung commented on trident/operation/softmax.py
> +            return (size_against_dim,)
네 맞습니다. `x_size`, `y_size`를 넘겨주고 커널에서 `size_along_dim`, `size_against_dim`을 계산해주세요. 지금 코딩 스타일이 이런데 티타임에 이야기해서 어느것을 넘기는게 좋을지 이야기해봐요.

2023-08-17 08:10 UTC, kakao-steve-ai commented on trident/operation/softmax.py
> +            return (size_against_dim,)
넵

2023-08-17 08:14 UTC, daemyung commented on trident/kernel/softmax.py
> +            stride_0 = 1
이렇게 하더라도 stride_0, stride_1이 필요한가요?

2023-08-17 08:23 UTC, ansteve commented on trident/kernel/softmax.py
> +            stride_0 = 1
이것도 코딩스타일 문제인거 같습니다. 아래쪽 `make_block_ptr`에서 반복적으로 `strides = (1, size_against_dim) if dim == 0 else (size_along_dim, 1)` 하는것보다 이 방식이 좋다고 생각했습니다. 다른 옵션으로, 새로운 변수 선언하고 그것을 `make_block_ptr`에서 사용하려고 했을때는 컴파일 에러가 발생했고요.

2023-08-17 09:17 UTC, daemyung commented on trident/kernel/softmax.py
> +            stride_0 = 1
음 그렇군요. 그렇다면 `size_along_dim`은 `j_size`로 `size_against_dim`은 `i_size`로 변경 부탁드립니다. `stride_0`도 `j_stride`로 `stride_1`은 `i_stride`로 변경 부탁드려요. `x, y, z`가 dim에 따라 재정렬된 축이 `i, j, k`로 대응하는게 좋을 것 같습니다. 그리고 이렇게 코딩 스타일을 정하면 `i_size`, `j_size`, `i_stride`, `j_stride`가 무조껀 필요하게 되는데 기존처럼 모두 호스트 쪽에서 계산해서 넘겨주세요.

2023-08-18 00:44 UTC, ansteve commented on trident/kernel/softmax.py
> +            stride_0 = 1
`x_size`, `y_size`, `x_stride`, `y_stride` 로 하는게 제일 깔끔한거 같습니다.

2023-08-18 00:45 UTC, daemyung approved these changes
LGTM, 고생하셨습니다.

2023-08-18 00:45 UTC, daemyung commented on trident/kernel/softmax.py
> +            stride_0 = 1
저도 그렇게 생각됩니다. 이 방법을 정착 시키죠.

2023-08-18 01:15 UTC, merged