Fix bugs in Softmax
kakaobrain/trident pull request #6
Opened 2023-06-20 11:41 UTC by rbbang

## 🙏 Describe the pull request

* Softmax의 잘못된 역전파 함수를 수정하고 테스트를 추가했습니다. 

## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

2023-06-20 13:25 UTC, daemyung commented
@rbbang 참고로 커널 작성은 지금하지 않으셔도 됩니다.

2023-06-21 00:28 UTC, rbbang commented
> @rbbang 참고로 커널 작성은 지금하지 않으셔도 됩니다.

네 그러면 일단은 kernel 호출하는 부분은 지우고 PR 올리겠습니다

2023-06-21 00:32 UTC, daemyung commented
> > @rbbang 참고로 커널 작성은 지금하지 않으셔도 됩니다.
> 
> 
> 
> 네 그러면 일단은 kernel 호출하는 부분은 지우고 PR 올리겠습니다

천천히 작업하셔도 됩니다. 커널 작성법을 배우고 PR을 반영해도 좋습니다.

2023-06-21 01:51 UTC, daemyung requested changes
`kernel.softmax_backward` 삭제 부탁드려요.

2023-06-21 01:51 UTC, daemyung commented on trident/operation/softmax.py
> +        grad = torch.empty_like(y)
변수 이름을 grad 대신에 `grad_x`로 쓰는게 좋을 것 같습니다.

2023-06-21 01:54 UTC, rbbang commented on trident/operation/softmax.py
> +        grad = torch.empty_like(y)
넵 수정하였습니다

2023-06-21 01:55 UTC, daemyung approved these changes
LGTM

2023-06-21 02:02 UTC, merged