Add fp16 tests and fix softmax, max_pool2d, avg_pool2d to support it
kakaobrain/trident pull request #9
Opened 2023-06-26 10:25 UTC by rbbang

## 🙏 Describe the pull request

인풋 텐서 타입이 fp16인 경우에 대한 테스트를 추가했습니다.
테스트 추가 후 발견된 이슈들에 대한 픽스를 넣었습니다.
softmax의 경우, fp16을 fp32로 변환후 계산을 수행하였습니다.(tl.exp, tl.max 함수등이 fp16을 지원하지 않음)
max_pool2d, adaptive_avg_pool2d의 경우 결과만 fp16으로 변화해주었습니다. 

## ✅ Checklist

- [ ] Code follows the project's coding conventions and style.
- [ ] Tests have been added or updated to cover the changes.
- [ ] Documentation has been updated, if necessary.

2023-06-26 10:42 UTC, rbbang commented
테스트들 중에 input2d, input3d, input4d, target을 사용하지 않고, 함수 안에서 새로 텐서를 생성해서 사용하는 경우도 있는데 이런 경우는 어떻게 커버할지 고민중입니다.

2023-06-26 23:04 UTC, daemyung requested changes

2023-06-26 23:04 UTC, daemyung commented on tests/conftest.py
> +def input2d(dtype):
`input` 변수들은 나중에 없어질 예정입니다. `input` 변수를 수정하지 말고 테스트 케이스에서 `dtype`을 받아서 텐서를 생성하세요.

2023-06-26 23:04 UTC, daemyung commented on trident/operation/softmax.py
> +        dt = x.dtype
변수 이름은 `dt`보다 `dtype`이 적합해 보입니다.

2023-06-26 23:04 UTC, daemyung commented on trident/operation/softmax.py
> +        if dt == torch.float16:
이러한 형변환은 커널에서 실행 되어야 합니다.

2023-06-26 23:05 UTC, daemyung commented
@rbbang 커밋 제목으로 작성한 내용은 커밋 본문으로 이동되는게 더 적합해 보입니다. 커밋 제목은 더 간결하게 작성해 주세요.

2023-06-27 04:30 UTC, rbbang commented on tests/conftest.py
> +def input2d(dtype):
네 수정하였습니다.

2023-06-27 04:30 UTC, rbbang commented on trident/operation/softmax.py
> +        dt = x.dtype
softmax는 나중에 작업하겠습니다.

2023-06-27 04:31 UTC, rbbang commented on trident/operation/softmax.py
> +        if dt == torch.float16:
네 이 부분 나중에 작업하겠습니다.

2023-06-27 04:31 UTC, rbbang commented
> @rbbang 커밋 제목으로 작성한 내용은 커밋 본문으로 이동되는게 더 적합해 보입니다. 커밋 제목은 더 간결하게 작성해 주세요.

커밋 제목 간결하게 바꾸고, 본문으로 내용 이동시켰습니다.

2023-06-28 08:29 UTC, daemyung approved these changes
LGTM

2023-06-28 08:32 UTC, merged