Fix benchmark of linear backward
kakaobrain/trident pull request #90
Opened 2023-09-01 08:20 UTC by mejai1206

## 🙏 Describe the pull request
Linear Bacward 벤치마크에서 grad를 계산하지 않는점 수정하였습니다.

## 💬 Additional context
input, weight, bias의 grad를 구할 경우 벤치마크입니다.

![image](https://github.com/kakaobrain/trident/assets/117069362/8d554aec-1364-465f-9d9e-21bd2a264d99)
## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

2023-09-01 08:22 UTC, ansteve approved these changes
LGTM

2023-09-01 10:55 UTC, daemyung commented on benchmarks/benchmark_linear.py
> +    input.requires_grad = operation.weight.requires_grad = operation.bias.requires_grad = True
이게 있어야지되요? `no_grad` 아니면 되는거 아니에요?

2023-09-01 10:55 UTC, daemyung commented on benchmarks/benchmark_linear.py
> +    grad_output = torch.ones_like(output)
`ones`으로 바꾼 이유가 있을까요?

2023-09-01 11:20 UTC, daemyung commented
@mejai1206 역전파를 벤치마크할때 함수를 사용해서 측정하세요.

2023-09-01 11:28 UTC, daemyung requested changes
역전파를 벤치마크할때 함수를 사용하면 `use_accelerator`를 사용할 수 있습니다.

2023-09-03 23:28 UTC, mejai1206 commented on benchmarks/benchmark_linear.py
> +    grad_output = torch.ones_like(output)
`torch.randn(output)` 이 컴파일 오류가 나기도 하고, 
`output`과 `shape`이나 기타 속성이 일치하는 텐서를 넣기만 하면 상관없다고 생각했습니다.

2023-09-03 23:40 UTC, mejai1206 commented on benchmarks/benchmark_linear.py
> +    input.requires_grad = operation.weight.requires_grad = operation.bias.requires_grad = True
trident는 `requires_grad` 값과 상관없이 역전파를 계산하지만 `torch`는  `requires_grad=Ture`가 아니면
역전파를 계산하지 않습니다. 이러면 공정한 비교가 아니기 때문에 수정하게 되었습니다.

2023-09-04 00:35 UTC, mejai1206 commented
`use_accelerator` 를 사용하기 위해 아래와 같이 변경하였습니다.


```
def bench_linear_backward(m_size, n_size, k_size, backend):
    input = torch.randn(m_size, k_size, device="cuda", requires_grad=True)
    weight = torch.randn(n_size, k_size, device="cuda", requires_grad=True)
    bias = torch.randn(n_size, device="cuda", requires_grad=True)

    if backend == "torch":
        output = torch.nn.functional.linear(input, weight, bias)
    else:
        output = trident.function.linear(input, weight, bias, use_accelerator=True)

    grad_output = torch.ones_like(output)

    return triton.testing.do_bench_cudagraph(lambda: output.backward(grad_output, retain_graph=True))
```

2023-09-04 00:54 UTC, daemyung requested changes
커밋 메세지 `Fix bugs in Linear benchmark`로 수정 부탁드려요. 커밋 메세지에 연산은 대문자로 쓰고 있어요.

2023-09-04 00:54 UTC, daemyung commented on benchmarks/benchmark_linear.py
> +    grad_output = torch.ones_like(output)
`rand_link`로 바꿔주시겠어요? `ones_like`를 사용하면 계산 결과가 달라도 발견되지 않는 문제가 있더라고요.

2023-09-04 01:01 UTC, daemyung approved these changes
LGTM

2023-09-04 01:25 UTC, merged