Support bfloat16 for Linear backward
kakaobrain/trident pull request #98
Opened 2023-09-04 08:47 UTC by ansteve

## 🙏 Describe the pull request

* Linear backward가 bfloat16, float16에 대하여 작동하도록 수정합니다.

## ✅ Checklist

- [x] Code follows the project's coding conventions and style.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

2023-09-04 08:55 UTC, daemyung requested changes
연산은 클래스 이름과 동일하게 사용합니다. `Support bfloat16 for Linear backward`처럼 써주세요.

2023-09-04 08:55 UTC, daemyung commented on tests/test_linear.py
> +def test_backward(num_batches, m_size, n_size, k_size, device, dtype):
이런 문제가 있군요. 여기에 추가하지 말고 `test_linear`에다가 역전파도 실행하도록 해서 테스트 만들어주세요.

2023-09-04 08:57 UTC, ansteve commented on tests/test_linear.py
> +def test_backward(num_batches, m_size, n_size, k_size, device, dtype):
네 알겠습니다

2023-09-04 08:58 UTC, daemyung commented on tests/test_linear.py
> +def test_backward(num_batches, m_size, n_size, k_size, device, dtype):
`test_backward`에 추가하면 결과까지 검증해서 지난번에 결정했던 사항과 달라져요.

2023-09-04 09:17 UTC, mejai1206 commented on trident/language/linear.py
> +            grad_input += tl.dot(grad_output, weight, use_accelerator).to(dtype)
혹시 `grad_input`을 모두 누적시키고 저장시킬때 타입캐스팅을 하면 오류가 발생할까요?

2023-09-04 09:28 UTC, daemyung commented on trident/language/linear.py
> +            grad_input += tl.dot(grad_output, weight, use_accelerator).to(dtype)
`grad_input`을 `dot`의 결과 타입으로 선언하고 나중에 한번만 케스팅하는게 좋겠네요.

2023-09-04 10:07 UTC, ansteve commented on trident/language/linear.py
> +            grad_input += tl.dot(grad_output, weight, use_accelerator).to(dtype)
`tl.dot` 아규먼트 중에 `out_dtype` 이라는게 있네요. 이거를 이용하는게 속도면에서 이점이 있을 것 같습니다.

2023-09-04 10:22 UTC, ansteve commented on trident/language/linear.py
> +            grad_input += tl.dot(grad_output, weight, use_accelerator).to(dtype)
`out_dtype` 이용하니까 triton compiler 에러가 나네요. 마지막에 캐스팅하는 방식으로 수정하겠습니다.

2023-09-04 11:59 UTC, daemyung commented on trident/language/linear.py
> +            grad_input += tl.dot(grad_output, weight, use_accelerator).to(dtype)
@ansteve Triton에 이슈 리포트 부탁드려요.

2023-09-04 12:00 UTC, daemyung requested changes

2023-09-04 12:00 UTC, daemyung commented on tests/test_linear.py
> +    def train(func):
여기선 `train` 함수가 중복으로 쓰이지 않으니 그냥 바로 호출해주시겠어요?

2023-09-05 01:28 UTC, kakao-steve-ai commented on tests/test_linear.py
> +    def train(func):
네 수정하겠습니다

2023-09-05 01:28 UTC, ansteve commented on trident/language/linear.py
> +            grad_input += tl.dot(grad_output, weight, use_accelerator).to(dtype)
네 리포트하겠습니다

2023-09-05 04:17 UTC, ansteve commented on trident/language/linear.py
> +            grad_input += tl.dot(grad_output, weight, use_accelerator).to(dtype)
리포트하려고 좀 찾아보니까 이미 등록된 이슈네요. https://github.com/openai/triton/issues/2156

2023-09-05 04:30 UTC, mejai1206 approved these changes
LGTM

2023-09-05 04:35 UTC, daemyung requested changes

2023-09-05 04:35 UTC, daemyung commented on tests/test_linear.py
> +    weight = torch.randn(n_size, k_size, **factory_kwargs)
마지막으로 수정하면 될 것 같은데요. `input`, `weight`, `bias`는 `forward`, `backward`에 모두 사용되니까 처음부터 required_grad=True로 생성하고 테스트 케이스를 작성하시면 됩니다.

2023-09-05 04:38 UTC, mejai1206 commented on tests/test_linear.py
> +    weight = torch.randn(n_size, k_size, **factory_kwargs)
그러고보니까 이제 linear_test에서 `use_accelerator` 꺼야 하지 않나요?

2023-09-05 04:39 UTC, ansteve commented on tests/test_linear.py
> +    weight = torch.randn(n_size, k_size, **factory_kwargs)
넵

2023-09-05 04:40 UTC, daemyung commented on tests/test_linear.py
> +    weight = torch.randn(n_size, k_size, **factory_kwargs)
여기서는 동작 여부만 검사하기 때문에 켜도 상관 없어요.

2023-09-05 04:41 UTC, ansteve commented on tests/test_linear.py
> +    weight = torch.randn(n_size, k_size, **factory_kwargs)
https://github.com/kakaobrain/trident/blob/main/trident/function/function.py#L163
function에는 default로 꺼져있네요.

2023-09-05 04:49 UTC, mejai1206 commented on tests/test_linear.py
> +    weight = torch.randn(n_size, k_size, **factory_kwargs)
아 네네 없어도 괜찮겠군요.

2023-09-05 05:07 UTC, daemyung commented on tests/test_linear.py
> +    input.requires_grad = weight.requires_grad = bias.requires_grad = True
`input = torch.randn(m_size, k_size, **factory_kwargs, required_grad=True)`로 생성할 수 있어요.

2023-09-05 05:08 UTC, ansteve commented on tests/test_linear.py
> +    input.requires_grad = weight.requires_grad = bias.requires_grad = True
아 그렇네요. 수정하겠습니다.

2023-09-05 05:12 UTC, daemyung approved these changes
LGTM

2023-09-05 05:27 UTC, merged